feat: add mesh enable config and process url in mesh mode
apache/dubbo pull request #10356
Opened 2022-07-22 08:02 UTC by conghuhu

## What is the purpose of the change

ApplicationConfig adds meshEnable configuration, ReferenceConfig adds providerPort configuration, and at the same time, api configuration, xml configuration, attribute configuration, and annotation configuration are modified.

After meshEnable is true, the registry is set to N/A, at least one tri protocol needs to be configured, and the ports configured by the default consumer and provider are the same. DubboReference only needs to configure providedBy (K8S Service name == provider application name) to call.

```properties
# dubbo-consumer.properties
dubbo.application.name=dubbo-samples-mesh-consumer
dubbo.registry.address=N/A
dubbo.protocol.name=tri
dubbo.protocol.port=50052
# enable mesh
dubbo.application.meshEnable=true
```
```java
// consumer
@DubboReference(providedBy = "dubbo-samples-mesh-provider")
private Greeter greeter;
```
If the provider and consumer service ports are inconsistent, you need to configure the port exposed by the provider in DubboReference, as follows:
```java
// consumer
@DubboReference(providedBy = "dubbo-samples-mesh-provider", providerPort = 50052)
private Greeter greeter;
```

## Brief changelog

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2022-07-23 08:22 UTC, wangchengming666 approved these changes
test passed on my pc

2022-07-25 12:29 UTC, CrazyHZM requested changes

2022-07-25 12:29 UTC, CrazyHZM commented on dubbo-common/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java
> +    protected Integer providerPort;
Need to consider the multi-port situation.

2022-07-25 12:29 UTC, CrazyHZM commented on dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
> +    private Boolean meshEnable;
`meshEnable` should be the behavior of the consumer and should be placed in the configuration of the consumer level

2022-08-01 06:51 UTC, CrazyHZM requested changes

2022-08-01 06:51 UTC, CrazyHZM commented on dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceBeanBuilder.java
> +
Remove useless code.

2022-08-01 06:51 UTC, CrazyHZM commented on dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceAttributes.java
> +
Remove useless code.

2022-08-01 06:51 UTC, CrazyHZM commented on dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
> +        AtomicInteger port = new AtomicInteger(DEFAULT_MESH_PORT);
Why use `AtomicInteger`?

2022-08-09 02:13 UTC, chickenlj commented on dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
> +    Integer DEFAULT_MESH_PORT = 80;
Can we make the default mesh port the same as triple's default port? I think the default `80` port is not helpful for users using Triple, which is probably the most common case.

2022-08-09 13:39 UTC, merged