Module config no support unexport
apache/dubbo pull request #10380
Opened 2022-07-28 05:36 UTC by owen200008

unexport add remove config

2022-07-28 06:55 UTC, BurningCN commented on dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
> +        moduleModel.getConfigManager().removeConfig(this);
ServiceBean/Config has removed from configManger in here 
![image](https://user-images.githubusercontent.com/43363120/181440418-de42482c-5501-4f0e-951b-bd2dffedf75c.png)

2022-07-28 11:20 UTC, owen200008 commented on dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
> +        moduleModel.getConfigManager().removeConfig(this);
it only destroy call

2022-07-28 11:20 UTC, owen200008 commented on dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
> +        moduleModel.getConfigManager().removeConfig(this);
你可以试下 unexport 然后再export 同样的service

2022-07-28 14:05 UTC, BurningCN commented on dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
> +        moduleModel.getConfigManager().removeConfig(this);
正常就应该是在ModuleModel销毁的时候对configManger做清空操作的。
ServiceConfig的export和unexport内部都不应该对configManager进行添加或者移除操作。

2022-07-28 15:19 UTC, owen200008 commented on dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
> +        moduleModel.getConfigManager().removeConfig(this);
应该这个词有点太随便了
当一个ref unexport的时候
1. config里面是否还要保留着这个ref相关的信息
2. 因为保存了相关的信息那么同样接口的ref就无法再创建了，是否合适

当然这个都是要跟设计有关，但是从来没说过一个service和ref是单例的，只有在destroy才需要销毁，至少2.7.x的service和ref的生命周期是跟unexport相关的

2022-07-28 15:40 UTC, BurningCN commented on dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
> +        moduleModel.getConfigManager().removeConfig(this);
我想了下，我刚才的理解还是有些偏差的。刚看了下每次ReferenceConfig#destroy的时候也会从configManager移除，所以对应ServiceConfig#unexport应该也有。不过我想这个逻辑是不是放在ServiceConfig里，而不是ServiceBean里？

2022-07-28 15:46 UTC, owen200008 commented on dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
> +        moduleModel.getConfigManager().removeConfig(this);
写这里原因是，加入是bean做的，所以删除也由它管理

2022-07-28 15:52 UTC, BurningCN commented on dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
> +        moduleModel.getConfigManager().removeConfig(this);
可以看如下demo，不是通过ServiceBean的方式，直接是ServiceConfig

![image](https://user-images.githubusercontent.com/43363120/181582137-12c2bfab-aa4d-4aa1-871c-7b0b85724956.png)

2022-07-28 16:00 UTC, owen200008 commented on dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
> +        moduleModel.getConfigManager().removeConfig(this);
加入和删除一起迁移到父类我觉得是OK的
目前还是保持统一在bean中加入和删除更合适

2022-07-28 16:55 UTC, BurningCN commented on dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
> +        moduleModel.getConfigManager().removeConfig(this);
> 应该这个词有点太随便了 当一个ref unexport的时候
> 
> 1. config里面是否还要保留着这个ref相关的信息
> 2. 因为保存了相关的信息那么同样接口的ref就无法再创建了，是否合适
> 
> 当然这个都是要跟设计有关，但是从来没说过一个service和ref是单例的，只有在destroy才需要销毁，至少2.7.x的service和ref的生命周期是跟unexport相关的

我又想了下，针对你上面提到的。在ModuleDeployer销毁的时候，在每个ServiceConfig#unexport发生之后就立马做了configManager的remove操作（所以你说的12情况都不存在），只是这个时机没有放在unexport里面。而且目前unexport操作目前基本都是在ModuleDeployer销毁时调用的，除非说使用者自己去执行了unexport，才出现你说的情况，但一般使用者不会去这么做。

不过按照目前的修改，将ServiceConfig的从configManager的移除逻辑放在unexport方法中也没问题。

2022-08-01 03:31 UTC, AlbumenJ requested changes

2022-08-01 03:31 UTC, AlbumenJ commented on dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
> +        moduleModel.getConfigManager().removeConfig(this);
这里需要考虑下循环依赖的问题，ModuleModel.destroy -> foreach -> ServiceBean.unexport -> ModuleModel.remove

2022-08-01 05:03 UTC, AlbumenJ commented
还有一个问题是 ServiceBean 的 unexport 方法是谁调用的，理论上用户不会直接使用 ServiceBean 的，一般都是使用的 ReferenceConfig。如果 ServiceBean 的 unexport 是来自框架的调用，那么应该由外面的销毁管理器来统一清理。
这里有一个依赖关系是 ModuleModel => ConfigManager => ReferenceConfig，理论上是不应该由后级直接向前级直接发起调用的（一些特殊场景除外，但是要尽量减少这种场景），否则会很容易出现循环依赖。

2022-08-01 06:11 UTC, owen200008 commented
> 还有一个问题是 ServiceBean 的 unexport 方法是谁调用的，理论上用户不会直接使用 ServiceBean 的，一般都是使用的 ReferenceConfig。如果 ServiceBean 的 unexport 是来自框架的调用，那么应该由外面的销毁管理器来统一清理。 这里有一个依赖关系是 ModuleModel => ConfigManager => ReferenceConfig，理论上是不应该由后级直接向前级直接发起调用的（一些特殊场景除外，但是要尽量减少这种场景），否则会很容易出现循环依赖。

我这边要做的就是service和ref的一个热加载的功能，service mesh里面控制面肯定也是需要这块的
1. 我原始是基于ServiceBean做export和unexport来实现的，我这边考虑改成用ServiceConfig去热加载服务，这样可以避开目前这个问题，我这边的实现这里应该是我用法问题

针对ServiceBean的代码增加我看了#8789 #8867 没有完全理解
1. 就是为什么不是加到自己成员的ModuleModel
2.  ModuleModel => ConfigManager => ServiceConfig 理论上是不应该由后级直接向前级直接发起调用的，这个我非常同意，对用户使用的是ServiceConfig和ReferenceConfig，因此难免会有操作上设计到管理类的变更，更极端一些我可能不希望包含这些类，我只想包含定义变更的接口让对应管理层来实现

2022-08-01 06:48 UTC, AlbumenJ commented
> 我这边要做的就是service和ref的一个热加载的功能，service mesh里面控制面肯定也是需要这块的

这里在 3.0 的最新版本中，最好是和 ModuleModel 一起来做的，一次热发布绑定到 ModuleModel 的生命周期。目前 Spring Context 也支持绑定到 ModuleModel 上，在 Spring Context 关闭后也会自动关闭 ModuleModel，然后连带清理环境。当然单个的 Config 也是支持独立热发布的。

> ModuleModel => ConfigManager => ServiceConfig

这里想到一个方式，是否可以 ServiceConfig 向 ConfigManager 发送初始化或者销毁的通知，由 ConfigManager 来决策是否销毁这个引用。

2022-08-01 08:55 UTC, owen200008 commented
> > 我这边要做的就是service和ref的一个热加载的功能，service mesh里面控制面肯定也是需要这块的
> 
> 这里在 3.0 的最新版本中，最好是和 ModuleModel 一起来做的，一次热发布绑定到 ModuleModel 的生命周期。目前 Spring Context 也支持绑定到 ModuleModel 上，在 Spring Context 关闭后也会自动关闭 ModuleModel，然后连带清理环境。当然单个的 Config 也是支持独立热发布的。
> 
> > ModuleModel => ConfigManager => ServiceConfig
> 
> 这里想到一个方式，是否可以 ServiceConfig 向 ConfigManager 发送初始化或者销毁的通知，由 ConfigManager 来决策是否销毁这个引用。

这样是可以的
目前我对注册进ConfigManager的用途没有深入研究过，因为目前在ModuleModel里面的deployer有exportservice这个保存的配置信息已经足够了，后期是打算全部放到ConfigManager，这边都删除掉吗？

2022-08-04 02:52 UTC, AlbumenJ commented
多实例化改造之后ModuleModel持有了 ConfigManager 和 ServiceRepository。和配置相关的放在 ConfigManager，和发布后服务相关的放在 ServiceRepositorory。Deployer 直接存储 exportedService 应该是有问题，最后都要收口到 ConfigManager 和 ServiceRepository。

2022-09-20 08:33 UTC, closed without merging