fix validate violations is swallowed by ValidationException for issue#10415
apache/dubbo pull request #10434
Opened 2022-08-10 02:03 UTC by sparkzxl

## What is the purpose of the change

## Brief changelog

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2022-08-10 02:22 UTC, sparkzxl commented
fix issue#10415

2022-08-10 13:11 UTC, AlbumenJ requested changes

2022-08-10 13:11 UTC, AlbumenJ commented on dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidator.java
>              throw new ValidationException(e.getMessage());
`javax.validation.ConstraintViolationException` might have potential serialization issue. Should be converted.

2022-08-12 15:38 UTC, liufeiyu1002 commented
`ConstraintViolationImpl `不同版本字段不一样， 新版本新增了字段，如果单纯这么包装的话 意义不大，只是拿到了你认为的有效信息，  最起码新的结果要实现 `ConstraintViolation` 接口

2022-09-08 06:27 UTC, chickenlj commented
Check conclustion in https://github.com/apache/dubbo/issues/10415

2022-09-08 06:27 UTC, closed without merging