issue 10558: optimize performance for triple protocol(3.0)
apache/dubbo pull request #10587
Opened 2022-09-08 14:31 UTC by icodening

## What is the purpose of the change
优化triple协议的性能

## Brief changelog
1.修改各种Command以支持HTTP2多路复用
2.构造`TripleClientStream`对象时变更为非阻塞

PS：测试数据参见 #10558

2022-09-09 03:34 UTC, chickenlj commented
The test failures need to be fixed first.

2022-09-09 04:20 UTC, icodening commented
关闭该pr并重新提交至3.1

2022-09-09 09:23 UTC, icodening commented
需要解决冲突

2022-09-09 12:39 UTC, EarthChen commented
fix ut & it

2022-09-15 12:24 UTC, icodening commented
单测与code style已修复，目前差sample没跑通，待修复

2022-09-21 02:42 UTC, guohao requested changes

2022-09-21 02:42 UTC, guohao commented on dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/transport/WriteQueue.java
> +    private volatile Channel channel;
This `channel` cloud be deleted cuz parent channel can be got from `cmd`'s stream channel

2022-10-12 12:10 UTC, guohao approved these changes
LGTM

2022-10-14 02:20 UTC, EarthChen approved these changes
LGTM

2022-10-14 02:55 UTC, AlbumenJ approved these changes

2022-10-22 07:37 UTC, merged