Adaptive loadbalance
apache/dubbo pull request #10745
Opened 2022-10-13 07:32 UTC by ningboliu

## What is the purpose of the change

issue 10571  
adaptive loadbalance

## Brief changelog

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2022-10-13 07:43 UTC, ningboliu commented
**基准测试**
环境
Linux version 3.10.0-1127.el7.x86_64
4C8G 
java version "11.0.16.1"
网络：内网千兆网络

启动参数：-Xms2048m -Xmx2048m -XX:+UseG1GC

2服务器

```java

Benchmark                      Mode  Cnt      Score      Error  Units
LoadBalance.adaptive          thrpt    4  12908.232 ± 2808.715  ops/s
LoadBalance.random            thrpt    4  13197.763 ± 2388.624  ops/s
LoadBalance.roundrobin        thrpt    4  11899.578 ± 6931.389  ops/s
LoadBalance.shortestresponse  thrpt    4  11052.168 ±  517.151  ops/s
```

3服务器

```java

LoadBalance.adaptive          thrpt    4  19371.779 ± 2645.146  ops/s
LoadBalance.random            thrpt    4  19628.743 ± 4685.654  ops/s
LoadBalance.roundrobin        thrpt    4  19630.657 ± 4619.797  ops/s
LoadBalance.shortestresponse  thrpt    4  19250.009 ± 4268.092  ops/s
```

2022-10-20 02:32 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/AdaptiveLoadBalanceFilter.java
> +    private static final ThreadPoolExecutor executor = new ThreadPoolExecutor(1, 1, 0L,TimeUnit.MILLISECONDS, new LinkedBlockingQueue<>(1024),
should be lazy init or use dubbo shared executor

2022-10-21 14:25 UTC, ningboliu commented
三轮基准测试结果
![image](https://user-images.githubusercontent.com/30331180/197219140-5225fd67-767d-4396-a215-a943f8654360.png)

2022-10-24 04:34 UTC, AlbumenJ requested changes

2022-10-24 04:34 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/AdaptiveLoadBalanceFilter.java
> +            new NamedInternalThreadFactory("Dubbo-framework-loadbalance-adaptive", true), new ThreadPoolExecutor.DiscardOldestPolicy());
should not create executor by default when user do not use this

2022-10-25 03:35 UTC, AlbumenJ requested changes

2022-10-25 03:35 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/AdaptiveLoadBalanceFilter.java
> +                        new NamedInternalThreadFactory("Dubbo-framework-loadbalance-adaptive", true), new ThreadPoolExecutor.DiscardOldestPolicy());
Register to `org.apache.dubbo.common.resource.GlobalResourcesRepository#registerDisposable`

2022-10-25 03:35 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AdaptiveMetrics.java
> +    private static final ConcurrentMap<String, AdaptiveMetrics> METRICS_STATISTICS = new ConcurrentHashMap<String,
Should not use static field to store status in Dubbo. Use scope bean instead

2022-11-01 00:19 UTC, AlbumenJ requested changes

2022-11-01 00:19 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/AdaptiveLoadBalanceFilter.java
> +@Activate(group = CONSUMER, order = -200000)
```suggestion
@Activate(group = CONSUMER, order = -200000, value = {"loadbalance:adaptive"})
```

2022-11-01 00:19 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/AdaptiveLoadBalanceFilter.java
> +    public void setApplicationModel(ApplicationModel scopeModel) {
replace to constructor

2022-11-01 00:19 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/AdaptiveLoadBalanceFilter.java
> +            scopeModel.getBeanFactory().registerBean(new AdaptiveMetrics());
Add into `ScopeBeanInitializer`

2022-11-01 00:19 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/AdaptiveLoadBalanceFilter.java
> +    }
move to constructor

2022-11-01 00:19 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/AdaptiveLoadBalanceFilter.java
> +    }
move to constructor

2022-11-01 00:19 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/AdaptiveLoadBalanceFilter.java
> +        return invocation.getInvoker().getUrl().getAddress() + ":" + invocation.getProtocolServiceKey();
replace to StringBuilder and set initial size to improve performance

2022-11-01 00:19 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/AdaptiveLoadBalanceFilter.java
> +                ProfilerEntry profilerEntry = (ProfilerEntry) invocation.getAttributes().get(Profiler.PROFILER_KEY);
handle NPE if `profilerEntry` is null

2022-11-01 00:19 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/AdaptiveLoadBalance.java
> +    }
move to constructor

2022-11-01 00:19 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/AdaptiveLoadBalance.java
> +        }
use `ScopeBeanInitializer`

2022-11-01 00:19 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/AdaptiveLoadBalance.java
> +        invocation.setAttachment(Constants.ADAPTIVE_LOADBALANCE_ATTACHMENT_KEY,attachmentKey);
use `attribute` would better?

2022-11-01 00:19 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/AdaptiveLoadBalance.java
> +    }
cache this in invocation attribute

2022-11-01 00:19 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/AdaptiveLoadBalance.java
> +        return timeout;
why read current invocation's timeout?

2022-11-01 00:19 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/AdaptiveLoadBalance.java
> +        int timeout1 = getTimeout(invoker2, invocation);
Are there some spell mistakes?

2022-11-25 03:22 UTC, ningboliu commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/AdaptiveLoadBalance.java
> +        invocation.setAttachment(Constants.ADAPTIVE_LOADBALANCE_ATTACHMENT_KEY,attachmentKey);
Need to pass parameters to provider

2022-11-25 08:44 UTC, AlbumenJ requested changes

2022-11-25 08:44 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/AdaptiveLoadBalanceFilter.java
> +public class AdaptiveLoadBalanceFilter implements ClusterFilter, ClusterFilter.Listener {
Move this filter to implement `Filter` would be better. The implementation are related with the actual provider address.

2022-11-25 08:44 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/AdaptiveLoadBalanceFilter.java
> +    }
Will this key be reused?

2022-11-25 12:16 UTC, ningboliu commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/AdaptiveLoadBalanceFilter.java
> +    }
used 2 times

2022-11-28 01:47 UTC, AlbumenJ requested changes

2022-11-28 01:47 UTC, AlbumenJ commented on dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/AdaptiveLoadBalanceTest.java
> +        System.out.println(sumInvoker5);
Print here is useless

2022-11-28 01:47 UTC, AlbumenJ commented on dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/AdaptiveLoadBalanceTest.java
> +        //这个估算值并不准确
comment in English

2022-11-28 01:47 UTC, AlbumenJ commented on dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/AdaptiveLoadBalanceTest.java
> +        System.out.println(sumInvoker3);
Print is useless in unit test

2022-12-13 07:35 UTC, AlbumenJ approved these changes
LGTM

2022-12-13 08:32 UTC, merged

2026-01-29 06:40 UTC, zrlw commented
@ningboliu 

<img width="1994" height="1176" alt="Image" src="https://github.com/user-attachments/assets/17227513-b59d-4b85-8dd8-e93c7ca8f413" />

<img width="2090" height="1324" alt="Image" src="https://github.com/user-attachments/assets/70322897-91cd-4b3d-836c-23cbdb2ba222" />

1. As long as the server responds normally, the currentProviderTime and currentTime will be updated to serviceTime. Then there will be a call to trigger getLoad. As long as there is no clock back, the branch ```if (metrics. currentProviderTime==metrics. currentTime)``` will be reached. Then it will be satisfied. The lastLatency will be set to timeout * 2L. Is this branch a maximum probability? So the actual RT will be overwritten, so is the design here reasonable?
2. As long as getLoad is called once, ```metrics. CurrentProvider Time==metrics. CurrentTime``` will not be satisfied, so what is the design purpose of this branch?
3. ```metrics. lastLatency = metrics. lastLatency >> multiple;``` Does the decay rate occur too quickly?

see details at https://github.com/apache/dubbo/issues/15810