feat: split rpcContext
apache/dubbo pull request #10798
Opened 2022-10-23 16:04 UTC by aamingaa

This is the pure version

2022-10-24 04:38 UTC, AlbumenJ requested changes
What is the difference between #10793

2022-10-26 02:32 UTC, AlbumenJ requested changes

2022-10-26 02:32 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java
> +        RpcContext.getServerContext().setObjectAttachments(map);
should not call this method here

2022-10-26 02:32 UTC, AlbumenJ commented on dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/RpcContext.java
> -        org.apache.dubbo.rpc.RpcContext.removeServerContext();
recover this API

2022-10-26 02:32 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/PenetrateAttachmentSelector.java
> +    Map<String, Object> selectReverse(Invocation invocation);
Add `RpcContextAttachment serverAttachement / clientResponse` param

2022-10-26 02:32 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcContext.java
> +        }
create a new class file for this

2022-10-26 02:32 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcContext.java
> +    };
override all methods in RpcContextAttachment, and proxy to serverResponse / clientResponse

2022-10-27 03:36 UTC, AlbumenJ requested changes

2022-10-27 03:36 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServerContextAttachment.java
> +            return RpcContext.getClientResponseContext().getAttachment(key);
Get from `serverResponse` first and then fall back to `clientResponse`

2022-10-27 03:36 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServerContextAttachment.java
> +            return RpcContext.getClientResponseContext().getObjectAttachment(key);
Get from `serverResponse` first and then fall back to `clientResponse`

2022-10-27 03:36 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServerContextAttachment.java
> +            return RpcContext.getServerResponseContext().removeAttachment(key);
Remove in both `serverResponse` and `clientResponse`

2022-10-27 03:36 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServerContextAttachment.java
> +            return RpcContext.getServerResponseContext().getAttachments();
Create a new map, add all attachments from `clientResponse` and `serverResponse`. `serverResponse` should override `clientResponse`.

2022-10-27 03:36 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServerContextAttachment.java
> +            return RpcContext.getServerResponseContext().getObjectAttachments();
Create a new map, add all attachments from `clientResponse` and `serverResponse`. `serverResponse` should override `clientResponse`.

2022-10-27 03:36 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServerContextAttachment.java
> +            RpcContext.getServerResponseContext().clearAttachments();
Clear both `serverResponse` and `clientResponse`

2022-10-27 03:36 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServerContextAttachment.java
> +            return RpcContext.getServerResponseContext().get();
Deprecated method. Proxy it to getAttachements()

2022-10-27 03:36 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServerContextAttachment.java
> +            return RpcContext.getServerResponseContext().set(key, value);
Deprecated method. Proxy it to `setAttachment`

2022-10-27 03:36 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServerContextAttachment.java
> +            return RpcContext.getServerResponseContext().remove(key);
Deprecated method. Proxy it to `removeAttachment`

2022-10-27 03:36 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServerContextAttachment.java
> +            return RpcContext.getServerResponseContext().get(key);
Deprecated method. Proxy it to `getAttachment`

2022-10-27 03:36 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServerContextAttachment.java
> +            return RpcContext.getServerResponseContext().copyOf(needCopy);
Internal method, should not be called. Throw exception directly. BTW, check the usage.

2022-10-27 03:36 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServerContextAttachment.java
> +            return RpcContext.getServerResponseContext().isValid();
Internal method, should not be called. Throw exception directly. BTW, check the usage.

2022-10-27 03:36 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java
> +        ExtensionLoader<PenetrateAttachmentSelector> selectorExtensionLoader = applicationModel.getExtensionLoader(PenetrateAttachmentSelector.class);
```suggestion
    public ContextFilter(ApplicationModel applicationModel) {
        ExtensionLoader<PenetrateAttachmentSelector> selectorExtensionLoader = applicationModel.getExtensionLoader(PenetrateAttachmentSelector.class);
```

2022-10-27 03:36 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/PenetrateAttachmentSelectorMock.java
> +    }
Add some test cases for this

2022-10-27 03:40 UTC, AlbumenJ reviewed
Please enhance the description in https://dubbo.apache.org/zh/docs3-v2/java-sdk/advanced-features-and-usage/service/attachment

2022-11-04 09:02 UTC, tracywenjin commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java
>                  }
第三方

2022-11-08 00:00 UTC, AlbumenJ requested changes

2022-11-08 00:00 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServerContextAttachment.java
> +            attachmentMap.putAll(getAllAttachmentMap());
what is the purpose of these two lines

2022-11-08 00:00 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/AbstractServerCallListener.java
>          RpcContext.getServerContext().setRemoteAddress(remoteAddress);
```suggestion
        RpcContext.getServiceContext().setRemoteAddress(remoteAddress);
```

2022-11-08 00:00 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/AbstractServerCallListener.java
>              RpcContext.getServerContext().setRemoteApplicationName(remoteApp);
```suggestion
        RpcContext.getServiceContext().setRemoteApplicationName(remoteApp);
```

2022-11-08 00:00 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/AbstractServerCallListener.java
> +        };
```suggestion
        }
```

2022-11-10 12:56 UTC, AlbumenJ approved these changes
LGTM

2022-11-10 12:56 UTC, merged