Compatible with Springframework 6 removed class InstantiationAwareBeanPostProcessorAdapter (#10953)
apache/dubbo pull request #10954
Opened 2022-11-18 03:30 UTC by gitchenjh

## What is the purpose of the change
Fix #10953 

## Brief changelog
remove class `org.springframework.beans.factory.config.InstantiationAwareBeanPostProcessorAdapter`  because it's removed in Springframework 6

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2022-11-19 13:07 UTC, weixsun commented
@gitchenjh This is a duplicate of #10697, and it has been merged into the 3.2 branch.

Additionally, work to support Spring 6 and Spring Boot 3 will be done in #10941, which will then also be merged into the 3.2 branch.

2022-11-21 02:24 UTC, chickenlj approved these changes
LGTM.

2022-11-21 02:47 UTC, AlbumenJ requested changes
Duplicated with https://github.com/apache/dubbo/pull/10697.
BTW, the `3.1` branch should not merge in any feature due to stability considerations.

2022-11-21 03:21 UTC, gitchenjh commented
duplicated

2022-11-21 03:21 UTC, closed without merging