update: support anonymous access.
apache/dubbo pull request #11076
Opened 2022-12-05 16:22 UTC by Koooooo-7

## What is the purpose of the change
> Background: Dubbo QoS supports docking with kubernetes probes, but foreignIp needs to be enabled. Due to the high-risk instructions in qos, this will lead to a series of security problems.
We should distinguish those commands with low-risk and high-risk, and support all client to request low-risk command for healthy check or metrics collection purpose.

TODO:
-  Indicate the permission level for each cmd.
- related test cases.

close #11015 

## Brief changelog

Add new config `qos.anonymous.access.permission.level` to enable any foreign ip access. Default is `Cmd.PermissionLevel.NONE`, can not access any cmd (equivalent to disable the anonymous access config).

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2022-12-06 14:04 UTC, Koooooo-7 commented
Hi @AlbumenJ , PTAL.

2022-12-07 11:44 UTC, AlbumenJ requested changes
Please rebase this PR onto `3.2` branch.

2022-12-07 11:49 UTC, AlbumenJ requested changes

2022-12-07 11:49 UTC, AlbumenJ commented on dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/annotation/Cmd.java
> +
Move out as a public class

2022-12-07 11:49 UTC, AlbumenJ commented on dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/DefaultAnonymousAccessPermissionChecker.java
> +}
Is it really necessary to create this class separately.

2022-12-07 13:59 UTC, Koooooo-7 commented on dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/annotation/Cmd.java
> +
updated.

2022-12-07 14:10 UTC, Koooooo-7 commented
> Please rebase this PR onto `3.2` branch.

As per the large diff of commits between `3.1` to `3.2` now, It seems hard to rebase the pr to `3.2` , unless making this pr mess with other commits which already in `3.1` (include  `qos` updates). I suggest to merge it in `3.1` and sync to `3.2` later.

2022-12-09 08:35 UTC, AlbumenJ requested changes

2022-12-09 08:35 UTC, AlbumenJ commented on dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java
> +            String anonymousAccessPermissionLevel = url.getParameter(ANONYMOUS_ACCESS_PERMISSION_LEVEL, PermissionLevel.NONE.name());
Default level could be public.

2022-12-09 11:41 UTC, Koooooo-7 commented on dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java
> +            String anonymousAccessPermissionLevel = url.getParameter(ANONYMOUS_ACCESS_PERMISSION_LEVEL, PermissionLevel.NONE.name());
updated.

2022-12-09 13:53 UTC, Koooooo-7 commented
It seems there has IT issue same to branch `3.2` latest commit.

2022-12-12 07:22 UTC, AlbumenJ approved these changes
LGTM. Would you please add some document for this PR in dubbo-website.

2022-12-12 07:22 UTC, merged