消费者filter
apache/dubbo pull request #11452
Opened 2023-02-03 07:49 UTC by lcb11

## What is the purpose of the change

## Brief changelog

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2023-02-03 09:00 UTC, songxiaosheng commented
please use English

2023-02-04 02:11 UTC, lcb11 commented
> please use English

ok

2023-02-06 11:47 UTC, AlbumenJ requested changes

2023-02-06 11:47 UTC, AlbumenJ commented on dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MetricsFilterConsumer.java
> +public class MetricsFilterConsumer implements Filter, BaseFilter.Listener, ScopeModelAware {
Replace with `ClusterFilter`

2023-02-06 11:47 UTC, AlbumenJ commented on dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MetricsFilterConsumer.java
> +package org.apache.dubbo.metrics.filter;
Please add ASF license header

2023-02-06 11:47 UTC, AlbumenJ commented on dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MetricsFilterConsumer.java
> +import org.apache.dubbo.rpc.*;
do not use comma import

2023-02-06 11:47 UTC, AlbumenJ commented on dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MetricsFilterConsumer.java
> +    public void setApplicationModel(ApplicationModel applicationModel) {
```suggestion
    public MetricsFilterConsumer(ApplicationModel applicationModel) {
```

2023-02-06 11:47 UTC, AlbumenJ commented on dubbo-test/dubbo-test-check/pom.xml
> +        </dependency>
What is the purpose of changing this

2023-02-07 06:09 UTC, lcb11 commented on dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MetricsFilterConsumer.java
> +public class MetricsFilterConsumer implements Filter, BaseFilter.Listener, ScopeModelAware {
ok

2023-02-07 06:09 UTC, lcb11 commented on dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MetricsFilterConsumer.java
> +package org.apache.dubbo.metrics.filter;
ok

2023-02-07 06:10 UTC, lcb11 commented on dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MetricsFilterConsumer.java
> +import org.apache.dubbo.rpc.*;
ok, I will change this

2023-02-07 08:13 UTC, lcb11 commented on dubbo-test/dubbo-test-check/pom.xml
> +        </dependency>
sorry,  I didn't know this was change.

2023-02-07 08:31 UTC, AlbumenJ requested changes

2023-02-07 08:31 UTC, AlbumenJ commented on dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/ClusterFilter.java
> +    ApplicationModel applicationModel=null;
```suggestion
    private final DefaultMetricsCollector collector;
    private final ApplicationModel applicationModel;
```

2023-02-07 08:37 UTC, lcb11 commented on dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/ClusterFilter.java
> +    ApplicationModel applicationModel=null;
ok

2023-02-10 08:10 UTC, AlbumenJ requested changes

2023-02-10 08:10 UTC, AlbumenJ commented on dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/ClusterFilter.java
> +public class ClusterFilter implements Filter, BaseFilter.Listener, ScopeModelAware {
Rename.
`ClusterFilter` is duplicated.

2023-02-10 08:10 UTC, AlbumenJ commented on dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/filter/MetricsFilterTest.java
> +import org.apache.dubbo.rpc.*;
Do not use comma import.
You can import code style config in `codestyle` folder.

2023-02-10 08:10 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-triple/pom.xml
> +        </dependency>
`dubbo-rpc-triple` should not depends on `dubbo-all`

2023-02-10 08:10 UTC, AlbumenJ commented on dubbo-test/dubbo-test-check/pom.xml
> +        </dependency>
Still exist

2023-02-11 09:24 UTC, songxiaosheng requested changes

2023-02-13 06:09 UTC, closed without merging