Add Dubbo Annotation Processor (Add deprecated method warn when called by user, #10850)
apache/dubbo pull request #11513
Opened 2023-02-09 08:14 UTC by win120a

## What is the purpose of the change
Trying to provide a solution of #10850.

## Brief changelog
Adds an annotation processor, which adds a line of code in every methods decorated by `@Deprecated`. Like getServiceName() in class URL of dubbo-common module (decompiled result): 
```java
    @Deprecated
    public String getServiceName() {
        LoggerFactory.getErrorTypeAwareLogger(URL.class).warn("0-99", "invocation of deprecated method", "", "Deprecated method invoked. The method is org.apache.dubbo.common.URL.getServiceName()");
        return this.getServiceInterface();
    }
```

## Verifying this change
Use a decomplier (like Java Decompiler, or FernFlower decompiler in IntelliJ IDEA) to see the result.

2023-02-10 15:01 UTC, win120a commented
@AlbumenJ PTAL.

2023-02-14 01:48 UTC, AlbumenJ requested changes
Please rebase your branch onto `3.2`

2023-02-14 01:55 UTC, AlbumenJ requested changes

2023-02-14 01:55 UTC, AlbumenJ commented on NOTICE
> + */
No need to add notice if there is not NOTICE file in https://github.com/projectlombok/lombok.

2023-02-14 01:55 UTC, AlbumenJ commented on dubbo-annotation-processor/src/main/java/org/apache/dubbo/annotation/handler/DeprecatedHandler.java
> +            ASTUtils.addImportStatement(apContext, classSymbol, "org.apache.dubbo.common", "DeprecatedMethodInvocationCounter");
Just insert `DeprecatedMethodCollector.collect(xxx)` here. Log and count in `DeprecatedMethodCollector.collect`.

2023-02-14 01:56 UTC, AlbumenJ reviewed
Can the inserted code also inserted into `xxx-source.jar`?

2023-02-14 08:25 UTC, win120a commented
> Please rebase your branch onto `3.2` .

Rebased.

> Just insert DeprecatedMethodCollector.collect(xxx) here. Log and count in DeprecatedMethodCollector.collect.

Have moved all the logic to `org.apache.dubbo.common.DeprecatedMethodInvocationCounter#onDeprecatedMethodCalled()` .

> Can the inserted code also inserted into `xxx-source.jar`?

Unfortunately, it can't. It works as a compiler addon (an annotation processor). It directly modifes the Abstract Syntax Tree (i.e. the `.class` file), the source code remains untouched. Since the source plugin in Maven just copies the source, the generated sources.jar will not appear the modified code.

2023-02-20 08:23 UTC, AlbumenJ reviewed
@chickenlj PTAL

2023-03-06 07:07 UTC, AlbumenJ commented
![Uploading image.png…]()

2023-03-21 10:52 UTC, win120a commented
@AlbumenJ PTAL.
The scope configuration of pom.xml is required to import javac package (tools.jar), which causes 'bugs' in SonarLint.

2023-03-23 12:23 UTC, AlbumenJ requested changes

2023-03-23 12:23 UTC, AlbumenJ commented on dubbo-annotation-processor/src/main/java/org/apache/dubbo/annotation/permit/Permit.java
> + */
Leave the origin license here and add exclude in license checker.

2023-03-24 01:47 UTC, AlbumenJ approved these changes
LGTM

2023-03-24 01:48 UTC, merged