Code opt
apache/dubbo pull request #11857
Opened 2023-03-17 08:03 UTC by wxbty

## What is the purpose of the change
Code optimization
1. ServiceKeyMetric extracts the api package, and the metadata metrics can be reused.
2. skStats was originally used in the setKey scene, but now the num+1 scene is added, and it is changed to serviceNumStats and applicationNumStats to be more symmetrical
3. Delete redundant maps

2023-03-17 09:36 UTC, AlbumenJ approved these changes

2023-03-20 11:39 UTC, songxiaosheng requested changes

2023-03-20 11:39 UTC, songxiaosheng commented on dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/MetricsKeyWrapper.java
> +    // Register、subscribe、notify etc
can use doc comment such as /* */

2023-03-22 08:27 UTC, wxbty commented on dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/MetricsKeyWrapper.java
> +    // Register、subscribe、notify etc
ok

2023-03-23 13:50 UTC, songxiaosheng approved these changes
LGTM  @AlbumenJ PATL

2023-03-24 02:47 UTC, merged