binary search weights Fixes 11776
apache/dubbo pull request #11886
Opened 2023-03-23 03:33 UTC by eye-gu

## What is the purpose of the change

fix #11776 

## Brief changelog

## Verifying this change

## Checklist
- [ ] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2023-03-23 12:09 UTC, AlbumenJ requested changes
Please patch on 3.2 branch

2023-03-23 12:42 UTC, eye-gu commented
> Please patch on 3.2 branch

Submitted to 3.2 branch?

2023-03-24 05:29 UTC, EarthChen commented
> > Please patch on 3.2 branch
> 
> Submitted to 3.2 branch?

yep

2023-03-28 07:34 UTC, AlbumenJ approved these changes

2023-03-28 07:34 UTC, merged