optimize ThreadlessExecutor
apache/dubbo pull request #11965
Opened 2023-03-29 14:33 UTC by icodening

## What is the purpose of the change
1. optimize ThreadlessExecutor
2. tri response works on user threads

## Brief changelog

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2023-03-29 14:45 UTC, icodening commented on dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/ThreadlessExecutor.java
>      public boolean isWaiting() {
no need here, to be considered

2023-03-30 02:22 UTC, AlbumenJ approved these changes

2023-03-30 04:01 UTC, EarthChen requested changes

2023-03-30 04:01 UTC, EarthChen commented on dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java
> +                    call = new TripleClientCall(connectionClient, callbackExecutor,
The call should not be new twice

2023-04-10 10:55 UTC, EarthChen approved these changes
LGTM

2023-04-10 11:25 UTC, icodening commented on dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/ThreadlessExecutor.java
> +    private volatile Object waiter;
Only need to be visible to other threads

2023-04-11 02:52 UTC, merged

2023-09-28 02:47 UTC, vio-lin commented
timeout 超时回调加了一个 isShutdown的判断。  
我们线上也出现了 线程池被关掉的情况。 问下当时是有什么逻辑 触发了这个shutdonw 吗。
```
  ExecutorService executor = future.getExecutor();
            if (executor != null && !executor.isShutdown()) {
                executor.execute(() -> notifyTimeout(future));
            } else {
                notifyTimeout(future);
            }
```