fix ConcurrentHashMapUtils lock bug
apache/dubbo pull request #11987
Opened 2023-04-02 13:17 UTC by looly

## What is the purpose of the change

fix ConcurrentHashMapUtils lock bug

## Brief changelog

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2023-04-02 13:19 UTC, looly commented
issue : https://github.com/apache/dubbo/issues/11986

2023-04-03 08:31 UTC, AlbumenJ commented
![image](https://user-images.githubusercontent.com/9292748/229455235-1c7b27b0-5d31-44a3-951d-a21b4013baa8.png)

2023-04-04 09:25 UTC, AlbumenJ commented on dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java
> +        if (JRE.JAVA_8.isCurrentVersion()) {
这里应该任何版本的 JDK 都应该可以使用吧

2023-04-04 10:52 UTC, looly commented on dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java
> +        if (JRE.JAVA_8.isCurrentVersion()) {
并不是。这个bug在JDK8下会造成循环调用，但是jdk9+修复了这个问题，解决方式是有循环调用则抛出异常。这个test在jdk8下通过，jdk9+抛出异常。

2023-04-04 18:52 UTC, KamToHung reviewed
https://github.com/apache/dubbo/pull/6032
ExtensionLoader以前也遇到过这种问题，这样修改后代码健壮性挺好的

2023-04-05 06:26 UTC, AlbumenJ requested changes

2023-04-05 06:26 UTC, AlbumenJ commented on dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java
> +        if (JRE.JAVA_8.isCurrentVersion()) {
那基于 junit5 的注解做两个测试吧
现在 PR的 UT 只跑 JDK17，JDK 8 11 17 的全量测试只有 scheduled 的时候跑

2023-04-05 16:03 UTC, looly commented on dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java
> +        if (JRE.JAVA_8.isCurrentVersion()) {
@AlbumenJ 是这个意思么？我拆分成两个test。

2023-04-06 01:50 UTC, AlbumenJ commented on dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java
> +        if (JRE.JAVA_8.isCurrentVersion()) {
```
    @EnabledForJreRange(max = JRE.JAVA_8)
    @EnabledForJreRange(min = JRE.JAVA_9)
```

2023-04-06 01:51 UTC, AlbumenJ requested changes

2023-04-06 01:51 UTC, AlbumenJ commented on dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java
> +        if (JRE.JAVA_8.isCurrentVersion()) {
写两个 test，分别通过 EnabledForJreRange 配置运行的 jdk 版本

2023-04-13 08:36 UTC, looly commented on dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java
> +        if (JRE.JAVA_8.isCurrentVersion()) {
@AlbumenJ 辛苦看下。

2023-04-13 13:08 UTC, AlbumenJ commented on dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java
> +        // ConcurrentHashMapUtils.computeIfAbsent用于解决此问题，保证正常执行
Please comment in English

2023-04-20 07:56 UTC, AlbumenJ commented on dubbo-common/src/main/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtils.java
> +                v = func.apply(key);
Will this allocate more memory?

2023-04-20 08:00 UTC, looly commented on dubbo-common/src/main/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtils.java
> +                v = func.apply(key);
yes

2023-05-06 03:25 UTC, CrazyHZM requested changes

2023-05-06 03:25 UTC, CrazyHZM commented on dubbo-common/src/main/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtils.java
> +                v = func.apply(key);
Please check whether v is null.

2023-05-08 03:30 UTC, CrazyHZM approved these changes

2023-05-10 05:30 UTC, merged