Add metrics uts
apache/dubbo pull request #12089
Opened 2023-04-14 02:46 UTC by namelessssssssssss

## What is the purpose of the change
Provide unit test for dubbo-metrics.

## Brief changelog
* Add DefaultDubboClientObservationConventionTest in dubbo-metrics-api
* Add DefaultDubboServerObservationConventionTest in dubbo-metrics-api
* Add DefaultMetricsServiceTest in dubbo-metrics-default
* Add ThreadPoolMetricsSamplerTest in dubbo-metrics-default
* Add RegistryStatCompositeTest#testCalcServiceKeyRt() in dubbo-metrics-registry
## Verifying this change

2023-04-14 04:04 UTC, namelessssssssssss commented
@AlbumenJ @songxiaosheng  PTAL :)

2023-04-14 05:07 UTC, songxiaosheng reviewed
@namelessssssssssss

2023-04-14 05:07 UTC, songxiaosheng commented on dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/observation/DefaultDubboClientObservationConventionTest.java
> +@SuppressWarnings("deprecation")
Why add SuppressWarnings

2023-04-17 04:02 UTC, songxiaosheng commented
wait  me  look  obser starter

2023-04-19 04:44 UTC, songxiaosheng commented
@namelessssssssssss  please resolve conflicts

2023-04-20 08:20 UTC, AlbumenJ requested changes
Looks this PR is empty

2023-04-20 09:46 UTC, closed without merging