Feature/dubbo3.2 add rest client tls
apache/dubbo pull request #12251
Opened 2023-05-07 16:34 UTC by suncairong163

## What is the purpose of the change

add rest client tls

## Brief changelog

## Verifying this change

@AlbumenJ 

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2023-05-23 12:08 UTC, AlbumenJ requested changes

2023-05-23 12:08 UTC, AlbumenJ commented on dubbo-common/src/main/java/org/apache/dubbo/common/ssl/util/JDKSSLUtils.java
> +public class JDKSSLUtils {
```suggestion
public class JdkSslUtils {
```

2023-05-23 12:08 UTC, AlbumenJ commented on dubbo-common/src/main/java/org/apache/dubbo/common/ssl/util/pem/BASE64Decoder.java
> +public class BASE64Decoder {
`java.util.Base64` is enough?

2023-06-01 07:58 UTC, AlbumenJ requested changes

2023-06-01 07:58 UTC, AlbumenJ commented on dubbo-common/src/main/java/org/apache/dubbo/common/ssl/Cert.java
> +    }
Is it possible to match from context with regex?

2023-06-01 13:44 UTC, EarthChen approved these changes
LGTM.


Add more ut & it is better.

2024-09-11 16:07 UTC, closed without merging