feat:remove jprotoc dependency
apache/dubbo pull request #12343
Opened 2023-05-18 05:47 UTC by DreamerPXY

## What is the purpose of the change
dubbo-compiler remove jprotoc dependecy

## Brief changelog
1. Remove jprotc dependency and add mustache dependency for template generation code
2. Retain the ProtoTypeMap provided by the original jprotc for storing message types parsed from proto
3. Remove ProtocPlugin and use Dubbo's own DubboProtocPlugin as the main entry point for protoc plugin calls
4. DubboProtocPlugin no longer provides debug methods and only supports FEATURE_ PROTO3_ OPTIONAL

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2023-05-18 05:52 UTC, EarthChen requested changes

2023-05-18 05:52 UTC, EarthChen commented on dubbo-compiler/pom.xml
> +            <groupId>com.github.spullara.mustache.java</groupId>
format

2023-05-18 05:52 UTC, EarthChen commented on dubbo-compiler/README.md
> +## dubbo-complier移除jpotoc依赖
pls use english

2023-05-18 09:32 UTC, AlbumenJ commented
@guohao PTAL

2023-05-21 06:55 UTC, dongxuwang commented on dubbo-compiler/src/main/java/org/apache/dubbo/gen/AbstractGenerator.java
> +
I think this is the redundant blank line needs to be removed

2023-05-24 03:26 UTC, EarthChen commented
relate https://github.com/apache/dubbo/issues/12381

2023-10-19 02:34 UTC, closed without merging