Adds metrics initialization metrics for the service interface(#12850)
apache/dubbo pull request #12892
Opened 2023-08-14 06:00 UTC by robin977

Adds metrics initialization metrics for the service interface(#12850)

2023-08-14 07:50 UTC, AlbumenJ reviewed
@songxiaosheng @wxbty PTAL

2023-08-15 11:10 UTC, songxiaosheng commented
init metric as follow
<img width="930" alt="image" src="https://github.com/apache/dubbo/assets/81170548/41540004-a863-4074-9f7c-e79a3042e6d0">

2023-08-16 11:20 UTC, songxiaosheng approved these changes
LGTM

2023-08-16 11:45 UTC, wxbty requested changes

2023-08-16 11:45 UTC, wxbty commented on dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/data/MethodStatComposite.java
> +
The init method can directly set 0, no need to transfer parameters

2023-08-16 11:45 UTC, wxbty commented on dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollector.java
> +            }
RequestInitEvent and RequestEvent look different, one is triggered by app init, the other is triggered by rpc request, is it better to separate the listener?

2023-08-26 08:52 UTC, robin977 commented
![企业微信截图_705265f9-eee7-427e-8456-4cf3cffc1b99](https://github.com/apache/dubbo/assets/8486672/89c29292-0613-40ab-9020-b825d983ffb6)
![企业微信截图_db714257-9123-4f99-bca5-ff472448b4a4](https://github.com/apache/dubbo/assets/8486672/f8b0561f-f67c-4abf-b038-54b0fce65dcf)
![企业微信截图_340eefef-f167-4d51-b07e-846e75a78469](https://github.com/apache/dubbo/assets/8486672/e64aeaae-c693-41fd-9b26-221741393d23)

2023-08-26 10:06 UTC, wxbty requested changes

2023-08-26 10:06 UTC, wxbty commented on dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/event/MetricsInitEvent.java
> +        initEvent.putAttachment(MetricsConstants.INVOCATION, invocation);
Do not create immutable objects every time.

2023-08-26 10:11 UTC, wxbty requested changes

2023-08-26 10:11 UTC, wxbty commented on dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/event/DefaultSubDispatcher.java
> +                new MetricsCat(METRIC_REQUESTS_SUCCEED, (key, placeType, collector) -> AbstractMetricsKeyListener.onFinish(key,
Don't change that. Keep it the same as before

2023-08-26 12:53 UTC, wxbty commented
LGTM

2023-08-26 12:53 UTC, wxbty approved these changes

2023-08-26 12:54 UTC, merged