Split DefaultConfigValidator to SPI implements
apache/dubbo pull request #12948
Opened 2023-08-22 17:50 UTC by namelessssssssssss

## What is the purpose of the change
**As a part of dubbo-core refactor, we need to reduce DefaultConfigValidator's dependency on other modules.**

Example:
Some config validation operation depends on certain module APIs
```Java
//ConfigValidatorUtils
 public static void validateAbstractInterfaceConfig(AbstractInterfaceConfig config) {
        checkName(LOCAL_KEY, config.getLocal());
        checkName("stub", config.getStub());
        checkMultiName("owner", config.getOwner());
        checkExtension(config.getScopeModel(), ProxyFactory.class, PROXY_KEY, config.getProxy());
        checkExtension(config.getScopeModel(), Cluster.class, CLUSTER_KEY, config.getCluster());
        checkMultiExtension(config.getScopeModel(), Arrays.asList(Filter.class, ClusterFilter.class), FILTER_KEY, config.getFilter());
        checkNameHasSymbol(LAYER_KEY, config.getLayer());

        List<MethodConfig> methods = config.getMethods();
        if (CollectionUtils.isNotEmpty(methods)) {
            methods.forEach(ConfigValidationUtils::validateMethodConfig);
        }
    }
...

```
After refactor:
```Java
@Activate
public class InterfaceConfigValidator implements ConfigValidator<AbstractInterfaceConfig> {

    public static void validateAbstractInterfaceConfig(AbstractInterfaceConfig config) {
        ConfigValidationUtils.checkName(LOCAL_KEY, config.getLocal());
        ConfigValidationUtils.checkName("stub", config.getStub());
        ConfigValidationUtils.checkMultiName("owner", config.getOwner());

        ConfigValidationUtils.checkExtension(config.getScopeModel(), ProxyFactory.class, PROXY_KEY, config.getProxy());
        ConfigValidationUtils.checkExtension(config.getScopeModel(), Cluster.class, CLUSTER_KEY, config.getCluster());
        ConfigValidationUtils.checkMultiExtension(config.getScopeModel(), Arrays.asList(Filter.class, ClusterFilter.class), FILTER_KEY, config.getFilter());
        ConfigValidationUtils.checkNameHasSymbol(LAYER_KEY, config.getLayer());

        List<MethodConfig> methods = config.getMethods();
        if (CollectionUtils.isNotEmpty(methods)) {
            methods.forEach(MethodConfig::validate);
        }
    }

    @Override
    public void validate(AbstractInterfaceConfig config) {
        validateAbstractInterfaceConfig(config);
    }

    @Override
    public boolean isSupport(Class<?> configClass) {
        return AbstractInterfaceConfig.class.equals(configClass);
    }
}

```

## Brief changelog
* Turn interface ConfigValidator to SPI 
* Split DefaultConfigValidator to ConfigValidator implements.

This allows the configuration validation logic aggregated in DefaultConfigValidator to be distributed back into the ConfigValidator implements, reducing DefaultConfigValidator's dependency on other modules.

2023-09-04 09:02 UTC, chickenlj commented
LGTM.

2023-09-04 11:50 UTC, namelessssssssssss commented on dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
> +    String REGISTRY_SERVICE_CLASS_NAME = "org.apache.dubbo.registry.RegistryService";
This constant used to replace direct reference of `RegistryService` in `ConfigValidationUtils`

Old:
```Java
//ConfigValidationUtils.loadRegistries:214
                    map.put(PATH_KEY, RegistryService.class.getName());
```

New:
```Java
//ConfigValidationUtils.loadRegistries:127
                    map.put(PATH_KEY,REGISTRY_SERVICE_CLASS_NAME);
```

2023-09-05 03:51 UTC, AlbumenJ requested changes

2023-09-05 03:51 UTC, AlbumenJ commented on dubbo-common/src/main/java/org/apache/dubbo/config/context/AbstractConfigManager.java
>      private ConfigValidator getConfigValidator() {
Use `ConfigValidatorFacade` here

2023-09-05 06:56 UTC, namelessssssssssss commented
Some IT need fix after this PR merge:
```Java
//MetadataIt.test4
        } catch (IllegalArgumentException e) {  //TODO ->  catch (ConfigValidationException e)
            Assert.assertTrue(e.getMessage().contains("Please specify valid protocol or address for metadata report"));
        }
```

2023-09-07 10:49 UTC, AlbumenJ approved these changes

2023-09-10 12:56 UTC, AlbumenJ approved these changes

2023-09-10 12:56 UTC, merged