add ping pong for tri protocol
apache/dubbo pull request #12955
Opened 2023-08-24 15:37 UTC by icodening

## What is the purpose of the change
fix #12945
add ping pong for tri protocol

## Brief changelog
add fixed delay write ping frame handler

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2023-08-25 03:36 UTC, AlbumenJ requested changes

2023-08-25 03:36 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleWritePingHandler.java
> +        scheduledFuture = ctx.executor().scheduleWithFixedDelay(new WritePingTask(ctx.channel()), writePingIntervalInMs, writePingIntervalInMs, TimeUnit.MILLISECONDS);
Need a better way to write heartbeat.

2023-08-25 03:43 UTC, AlbumenJ requested changes

2023-08-25 03:43 UTC, AlbumenJ commented on dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyConnectionClient.java
> +                pipeline.addLast("client-idle-handler", new IdleStateHandler(idleTimeout, 0, 0, MILLISECONDS));
Need a idle handler and a close handler.

2023-08-25 15:35 UTC, icodening commented on dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleWritePingHandler.java
> +        scheduledFuture = ctx.executor().scheduleWithFixedDelay(new WritePingTask(ctx.channel()), writePingIntervalInMs, writePingIntervalInMs, TimeUnit.MILLISECONDS);
ok , i will redesign it

2023-08-29 06:22 UTC, EarthChen approved these changes
LGTM

2023-09-05 03:15 UTC, AlbumenJ commented
If we use port unification for both Dubbo and Triple protocol, will it work expectedly?

2023-09-05 11:01 UTC, icodening commented
> If we use port unification for both Dubbo and Triple protocol, will it work expectedly?

Only Triple protocol will handle `IDLE` state

2023-09-07 10:51 UTC, AlbumenJ commented
> > If we use port unification for both Dubbo and Triple protocol, will it work expectedly?
> 
> Only Triple protocol will handle `IDLE` state

But Dubbo protocol alose use `IDLE` state too

2023-10-11 01:38 UTC, AlbumenJ commented
@guohao pPTAL

2023-10-11 01:58 UTC, guohao approved these changes

2023-10-11 02:02 UTC, guohao commented
> > If we use port unification for both Dubbo and Triple protocol, will it work expectedly?
> 
> Only Triple protocol will handle `IDLE` state

Dubbo protocol's `IDEL` event can be supported in a seperated PR

2023-10-11 03:17 UTC, merged