java11+多classloader场景下，ClassPool初始化不能塞入父亲ClassPool为静态的defaultPool，否则d…
apache/dubbo pull request #13015
Opened 2023-09-06 09:21 UTC by veenter

目前这个bug据我观察，dubbo3全系都有，javassist使用不当所致。

如果当前环境是java11，存在多个classloader加载业务代码，每个classloader加载一个业务，且他们公用同一个dubbo框架实例，结构大致是：classloader1 里面放dubbo，classloader2加载BundleA，classloader3加载BundleB。

BundleA的classpath下，存在interfaceA的1.0版本，内部有3个method（method1、method2、method3）；BundleB的classpath下，存在interfaceA的1.1版本，内部有4个method（method1、method2、method3、method4，前3个方法与1.0版本一致，新增了一个method4）

开始启动，BundleA先启动，BundleB再启动，亦或者BundleA和BundleB多线程并行启动，但是走到关键代码的时候，是BundleA先走到（此处必须是BundleA先走到关键代码，否则bug不命中）

BundleB启动后会暴露一个interfaceA1.1版本的dubbo service

当外部业务调用请求到达，开始调用这个dubbo service的method4时，提示找不到method4
![image](https://github.com/apache/dubbo/assets/5327221/9698183f-4168-484d-bd2a-b1f1905351d1)

原写法：new ClassPool(ClassPool.getDefault()) ：初始化，设置一个父亲，父亲初始化的时候会追加tccl类所在classpath路径。这个父亲使用static方法创建，全局只有一个实例保存在类ClassPool内。

原写法会发生如下行为：
BundleA先到来，调用ClassPool.getDefault()，第一次初始化父亲，通过tccl把tccl类所在classpath加进去
BundleB再进来，调用ClassPool.getDefault()，已经存在，直接使用存在的
BundleB走到167行：classPool.get(c.getName())，获取的CtClass必然是BundleA的，CtClass使用父ClassPool从BundleA路径加载，因此ctMethods必然少了method4
被165-178行逻辑一处理，方法就丢了，导致后面生成的代理类少方法

161行替换为：final ClassPool classPool = new ClassPool(true);
让逻辑变成：谁进来，就使用自己的tccl来初始化ClassPool，彼此的ClassPool实例独立

2023-09-07 07:40 UTC, AlbumenJ commented
@qinliujie PTAL

2023-09-07 11:34 UTC, veenter commented on dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java
> +        final ClassPool classPool = new ClassPool(true);
确实是一样的。
我目前的改法是出于最小修改原则
如果要复用ClassGenerator的逻辑
那么就是删除161 162 163这三行
并替换为：final ClassPool classPool = ClassGenerator.getClassPool(cl);

同时另外同时发现ClassGenerator.getClassPool这个方法没有做线程安全，也需要修改：
![image](https://github.com/apache/dubbo/assets/5327221/22ff1865-3f90-4858-aaa7-cca178ea2fd6)

2023-09-07 11:55 UTC, veenter commented
另外有个问题想问：
163-176这段代码是做什么的？为了解决什么问题？我发现是https://github.com/apache/dubbo/pull/7927合并进来的，在这个之前是没有这段代码的

2023-09-08 13:56 UTC, veenter commented
我最新一次的提交终于让解决了sonarcloud的 https://sonarcloud.io/organizations/apache/rules?open=java%3AS2445&rule_key=java%3AS2445&tab=why 这个报错，但是现在的这个写法我真的是受不了，我认为这个检测是一个误报

原写法是这样的，很明显没有考虑线程安全
```
     public static ClassPool getClassPool(ClassLoader loader) {
        if (loader == null) {
            return ClassPool.getDefault();
        }

        ClassPool pool = POOL_MAP.get(loader);
        if (pool == null) {
            pool = new ClassPool(true);
            pool.insertClassPath(new LoaderClassPath(loader));
            pool.insertClassPath(new DubboLoaderClassPath());
            POOL_MAP.put(loader, pool);
        }
        return pool;
    }
```

第一次优化为下面这样，但检测出现了sonarcloud的报错
```
    public static ClassPool getClassPool(ClassLoader loader) {
        if (loader == null) {
            return ClassPool.getDefault();
        }

        ClassPool pool = POOL_MAP.get(loader);
        if (pool == null) {
            synchronized (loader) {
                pool = POOL_MAP.get(loader);
                if (pool == null) {
                    pool = new ClassPool(true);
                    pool.insertClassPath(new LoaderClassPath(loader));
                    pool.insertClassPath(new DubboLoaderClassPath());
                    POOL_MAP.put(loader, pool);
                }
            }
        }
        return pool;
    }
```

第二次我改成这样，依然不行
```
    public static ClassPool getClassPool(final ClassLoader loader) {
        if (loader == null) {
            return ClassPool.getDefault();
        }

        ClassPool pool = POOL_MAP.get(loader);
        if (pool == null) {
            synchronized (loader) {
                pool = POOL_MAP.get(loader);
                if (pool == null) {
                    pool = new ClassPool(true);
                    pool.insertClassPath(new LoaderClassPath(loader));
                    pool.insertClassPath(new DubboLoaderClassPath());
                    POOL_MAP.put(loader, pool);
                }
            }
        }
        return pool;
    }
```

最终我改成这样通过了sonarcloud检测，修改方案只是简单的赋值给一个final 变量，但是这样的写法也太愚蠢了
```
    public static ClassPool getClassPool(ClassLoader loader) {
        if (loader == null) {
            return ClassPool.getDefault();
        }
        //https://sonarcloud.io/organizations/apache/rules?open=java%3AS2445&rule_key=java%3AS2445&tab=why
        final ClassLoader currentLoader = loader;
        ClassPool pool = POOL_MAP.get(currentLoader);
        if (pool == null) {
            synchronized (currentLoader) {
                pool = POOL_MAP.get(currentLoader);
                if (pool == null) {
                    pool = new ClassPool(true);
                    pool.insertClassPath(new LoaderClassPath(currentLoader));
                    pool.insertClassPath(new DubboLoaderClassPath());
                    POOL_MAP.put(currentLoader, pool);
                }
            }
        }
        return pool;
    }
```

所以我认为sonarcloud的这个检测是有问题的。

而且我发现，搜索dubbo的整个代码库 类似这样的写法（锁方法参数）有好几处，不明白为何他们没被扫描到

比如：
![image](https://github.com/apache/dubbo/assets/5327221/983298f0-758d-44bc-96f1-de2060e55105)
![image](https://github.com/apache/dubbo/assets/5327221/7d5ebd12-85cd-4f4f-92d7-b380750b9d8c)
![image](https://github.com/apache/dubbo/assets/5327221/b8da27d2-a299-4314-ba34-c80a41395af6)
![image](https://github.com/apache/dubbo/assets/5327221/7b1ce6e6-6d76-4af0-b53d-9a3807abecdd)

2023-09-12 04:31 UTC, AlbumenJ commented
> final CtMethod[] ctMethods = classPool.get(c.getName()).getMethods()

https://github.com/apache/dubbo/pull/7517

2023-09-12 04:32 UTC, AlbumenJ commented
> 我最新一次的提交终于让解决了sonarcloud的 https://sonarcloud.io/organizations/apache/rules?open=java%3AS2445&rule_key=java%3AS2445&tab=why 这个报错，但是现在的这个写法我真的是受不了，我认为这个检测是一个误报
> 
> 原写法是这样的，很明显没有考虑线程安全
> 
> ```
>      public static ClassPool getClassPool(ClassLoader loader) {
>         if (loader == null) {
>             return ClassPool.getDefault();
>         }
> 
>         ClassPool pool = POOL_MAP.get(loader);
>         if (pool == null) {
>             pool = new ClassPool(true);
>             pool.insertClassPath(new LoaderClassPath(loader));
>             pool.insertClassPath(new DubboLoaderClassPath());
>             POOL_MAP.put(loader, pool);
>         }
>         return pool;
>     }
> ```
> 
> 第一次优化为下面这样，但检测出现了sonarcloud的报错
> 
> ```
>     public static ClassPool getClassPool(ClassLoader loader) {
>         if (loader == null) {
>             return ClassPool.getDefault();
>         }
> 
>         ClassPool pool = POOL_MAP.get(loader);
>         if (pool == null) {
>             synchronized (loader) {
>                 pool = POOL_MAP.get(loader);
>                 if (pool == null) {
>                     pool = new ClassPool(true);
>                     pool.insertClassPath(new LoaderClassPath(loader));
>                     pool.insertClassPath(new DubboLoaderClassPath());
>                     POOL_MAP.put(loader, pool);
>                 }
>             }
>         }
>         return pool;
>     }
> ```
> 
> 第二次我改成这样，依然不行
> 
> ```
>     public static ClassPool getClassPool(final ClassLoader loader) {
>         if (loader == null) {
>             return ClassPool.getDefault();
>         }
> 
>         ClassPool pool = POOL_MAP.get(loader);
>         if (pool == null) {
>             synchronized (loader) {
>                 pool = POOL_MAP.get(loader);
>                 if (pool == null) {
>                     pool = new ClassPool(true);
>                     pool.insertClassPath(new LoaderClassPath(loader));
>                     pool.insertClassPath(new DubboLoaderClassPath());
>                     POOL_MAP.put(loader, pool);
>                 }
>             }
>         }
>         return pool;
>     }
> ```
> 
> 最终我改成这样通过了sonarcloud检测，修改方案只是简单的赋值给一个final 变量，但是这样的写法也太愚蠢了
> 
> ```
>     public static ClassPool getClassPool(ClassLoader loader) {
>         if (loader == null) {
>             return ClassPool.getDefault();
>         }
>         //https://sonarcloud.io/organizations/apache/rules?open=java%3AS2445&rule_key=java%3AS2445&tab=why
>         final ClassLoader currentLoader = loader;
>         ClassPool pool = POOL_MAP.get(currentLoader);
>         if (pool == null) {
>             synchronized (currentLoader) {
>                 pool = POOL_MAP.get(currentLoader);
>                 if (pool == null) {
>                     pool = new ClassPool(true);
>                     pool.insertClassPath(new LoaderClassPath(currentLoader));
>                     pool.insertClassPath(new DubboLoaderClassPath());
>                     POOL_MAP.put(currentLoader, pool);
>                 }
>             }
>         }
>         return pool;
>     }
> ```
> 
> 所以我认为sonarcloud的这个检测是有问题的。
> 
> 而且我发现，搜索dubbo的整个代码库 类似这样的写法（锁方法参数）有好几处，不明白为何他们没被扫描到
> 
> 比如： org.apache.dubbo.common.beans.factory.ScopeBeanFactory#getOrRegisterBean(java.lang.String, java.lang.Class)
> 
> ```
> public <T> T getOrRegisterBean(String name, Class<T> type) {
>         T bean = getBean(name, type);
>         if (bean == null) {
>             // lock by type
>             synchronized (type) {
>                 bean = getBean(name, type);
>                 if (bean == null) {
>                     bean = createAndRegisterBean(name, type);
>                 }
>             }
>         }
>         registeredClasses.add(type);
>         return bean;
>     }
> ```
> 
> org.apache.dubbo.common.config.ConfigurationUtils#hasSubProperties(java.util.Map<java.lang.String,V>, java.lang.String)
> 
> ```
> public static <V extends Object> boolean hasSubProperties(Map<String, V> configMap, String prefix) {
>         if (!prefix.endsWith(".")) {
>             prefix += ".";
>         }
>         Map<String, V> copy;
>         synchronized (configMap) {
>             copy = new HashMap<>(configMap);
>         }
>         for (Map.Entry<String, V> entry : copy.entrySet()) {
>             String key = entry.getKey();
>             if (StringUtils.startsWithIgnoreCase(key, prefix)
>                 && key.length() > prefix.length()
>                 && !ConfigurationUtils.isEmptyValue(entry.getValue())) {
>                 return true;
>             }
>         }
>         return false;
>     }
> ```
> 
> org.apache.dubbo.common.config.configcenter.file.FileSystemDynamicConfiguration#executeMutually
> 
> ```
> private <V> V executeMutually(final Object mutex, Callable<V> callable) {
>         V value = null;
>         synchronized (mutex) {
>             try {
>                 value = callable.call();
>             } catch (Exception e) {
>                 if (logger.isErrorEnabled()) {
>                     logger.error(CONFIG_ERROR_PROCESS_LISTENER, "", "", e.getMessage(), e);
>                 }
>             }
>         }
>         return value;
>     }
> ```

sonarcloud 的我这边可以手动排除的

2023-09-12 04:36 UTC, AlbumenJ requested changes

2023-09-12 04:36 UTC, AlbumenJ commented on dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/ClassGenerator.java
> +        //https://sonarcloud.io/organizations/apache/rules?open=java%3AS2445&rule_key=java%3AS2445&tab=why
这个改成原来的吧，我直接忽略检查就行

2023-09-12 04:36 UTC, AlbumenJ commented on dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java
> +        final ClassPool classPool = ClassGenerator.getClassPool(cl);
如果这个池子共享了，是不是单独抽一个 util 类出来管理会好一些

2023-09-12 05:49 UTC, veenter commented on dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/ClassGenerator.java
> +        //https://sonarcloud.io/organizations/apache/rules?open=java%3AS2445&rule_key=java%3AS2445&tab=why
好的 ，我处理下

2023-09-12 05:57 UTC, veenter commented on dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java
> +        final ClassPool classPool = ClassGenerator.getClassPool(cl);
我的你的观点不一致：ClassPool池是ClassGenerator的一部分，而且我看ClassGenerator整个是管理字节码增强的，而且getClassPool还是一个public方法，ClassPool池也属于字节码增强的一部分，都放在ClassGenerator里管理不是更好。

你不你再看一下？

2023-09-13 01:54 UTC, AlbumenJ requested changes

2023-09-13 01:54 UTC, AlbumenJ commented on dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/ClassGenerator.java
> +            synchronized (loader) {
这里是不是直接使用当前 class 作为同步对象去弄，直接使用 loader 如果用户侧也是用了 loader 作为 metux 会出现死锁的

2023-09-13 02:24 UTC, veenter commented on dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/ClassGenerator.java
> +            synchronized (loader) {
你说的这个方式我知道，使用当前class、POOL_MAP、或者单独搞一个独立static final对象做为锁效果都可到达你要的，既所有的线程来到这里无论来自哪个classloader都会排队。但这与现在的写法完全不同了，现在是每个classloader都是独立的锁。

当然是有概率发生你说的事情的，调用这个方法的外部方法先锁住classloader，这样就会发生死锁。
那么现在就有2个选择：
1、使用classloader独立锁，多个Classloader调用的时候不发生锁冲突
2、为了避免问题1，共用同一个锁，必须发生classloader死锁问题

仔细分析了下，这个地方锁住等待的开销非常非常低，所以使用一个公共锁避免发生classloader死锁是对的，但是我觉得别说当前类了，锁POOL_MAP更好

这里我想说另一个问题：
dubbo的代码规范里，到底锁如何使用，我看到有锁入参的，也有使用公共锁的，按照现在的说法，锁入参的这些写法全部都有这种问题，我专门搜了dubbo代码，看大家都是怎么用的，发现五花八门

2023-09-13 04:58 UTC, AlbumenJ approved these changes

2023-09-14 06:29 UTC, qinliujie approved these changes
LGTM

2023-09-25 11:36 UTC, merged