optimize JVMUtil
apache/dubbo pull request #13334
Opened 2023-11-08 05:51 UTC by Linchen-Xu

## What is the purpose of the change
fix #13327 
- `dubbo.jstack-dump.max-line` can be used to indicate that all stack trace lines should be printed now by setting it to a negative number, -1 for example.
- write stack trace info directly into OutputStream instead of building a String

## Brief changelog
update org.apache.dubbo.common.utils.JVMUtil

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2023-11-08 09:10 UTC, AlbumenJ requested changes

2023-11-08 09:10 UTC, AlbumenJ commented on dubbo-common/src/main/java/org/apache/dubbo/common/utils/JVMUtil.java
> +                printStackDepth = Integer.parseInt(jstackMaxLineStr);
Seems should be `Math.min(stackTrace.length, Integer.parseInt(jstackMaxLineStr))`

2023-11-14 11:08 UTC, AlbumenJ requested changes

2023-11-14 11:08 UTC, AlbumenJ commented on dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/support/AbortPolicyWithReportTest.java
> +                JVMUtil.jstack(jStackStream);
Please add some test cases to verify the result

2023-11-14 18:29 UTC, Linchen-Xu commented
Due to a branch operation error, this PR is reopened in #13358.

2023-11-14 18:29 UTC, closed without merging