:bug: fix metrics servce level config bug
apache/dubbo pull request #13449
Opened 2023-12-01 06:03 UTC by songxiaosheng

## What is the purpose of the change

 servce level  config is init after application config be load

test result is such as:
<img width="1275" alt="image" src="https://github.com/apache/dubbo/assets/81170548/530a4795-172a-4a31-ba65-554c7c259a42">

## Brief changelog

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2023-12-01 12:13 UTC, AlbumenJ requested changes

2023-12-01 12:13 UTC, AlbumenJ commented on dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/report/AbstractMetricsExport.java
> +            synchronized (AbstractMetricsExport.class) {
Lock current object is enough

2023-12-01 12:13 UTC, AlbumenJ commented on dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/report/AbstractMetricsExport.java
> +    private Boolean serviceLevel;
Add `volatile`

2023-12-02 00:01 UTC, songxiaosheng commented
@AlbumenJ PATL

2023-12-04 01:34 UTC, merged