Fix local provider not found when bean initialize
apache/dubbo pull request #13713
Opened 2024-01-31 08:08 UTC by namelessssssssssss

* fix  https://github.com/apache/dubbo/issues/13672

2024-01-31 08:09 UTC, namelessssssssssss commented
@AlbumenJ PTAL

2024-01-31 08:09 UTC, namelessssssssssss commented on dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java
> +        if (serviceBean != null && !serviceBean.isExported() && SCOPE_LOCAL.equals(serviceBean.getScope())) {
Should we add `SCOPE_LOCAL.equals(serviceBean.getScope())` ?

2024-01-31 15:52 UTC, AlbumenJ requested changes

2024-01-31 15:52 UTC, AlbumenJ commented on dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java
> +                tryExportLocalProvider();
Export the service here is not a good idea. 
I think there might not exist an elegant resolution for such scenario.

2024-02-23 09:06 UTC, ShenFeng312 commented
I think this issue doesn't need to be fixed. If this usage is really necessary, why not use  @Service instead?

2024-07-11 10:30 UTC, closed without merging