fix dubbo demo xml double path error
apache/dubbo pull request #13789
Opened 2024-02-25 07:06 UTC by suncairong163

## What is the purpose of the change
fix #13640 

## Brief changelog

## Verifying this change
@AlbumenJ 

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2024-02-26 09:16 UTC, AlbumenJ approved these changes
LGTM
@CrazyHZM PTAL

2024-02-26 12:16 UTC, CrazyHZM requested changes

2024-02-26 12:16 UTC, CrazyHZM commented on dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/codec/JsonCodec.java
> +        //        unSupportClasses.add(String.class);
Please remove it.

2024-02-28 02:44 UTC, CrazyHZM approved these changes

2024-02-28 02:44 UTC, merged