test: add yaml loadAs test
apache/dubbo pull request #14080
Opened 2024-04-12 16:16 UTC by yuluo-yx

- For #13799

2024-04-23 15:31 UTC, oxsean requested changes
The background of this feature is that snakeyaml supports including class names within the content. Therefore, it's intended to test and verify that classes configured on the whitelist can be deserialized, whereas others should be rejected. 
e.g.,
```yaml
"1": !!demo.User
  name: Alice
  age: 28
"2": !!demo.User
  name: Bob
  age: 34
```

Refs:
https://github.com/apache/dubbo/blob/3.3/dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/message/codec/YamlCodec.java#L40
https://github.com/apache/dubbo/blob/3.3/dubbo-common/src/main/java/org/apache/dubbo/common/utils/DefaultSerializeClassChecker.java#L33
https://dubbo.apache.org/zh-cn/overview/mannual/java-sdk/advanced-features-and-usage/security/class-check/

2024-05-06 07:07 UTC, yuluo-yx commented
> The background of this feature is that snakeyaml supports including class names within the content. Therefore, it's intended to test and verify that classes configured on the whitelist can be deserialized, whereas others should be rejected. e.g.,
> 
> ```yaml
> "1": !!demo.User
>   name: Alice
>   age: 28
> "2": !!demo.User
>   name: Bob
>   age: 34
> ```
> 
> Refs: https://github.com/apache/dubbo/blob/3.3/dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/message/codec/YamlCodec.java#L40 https://github.com/apache/dubbo/blob/3.3/dubbo-common/src/main/java/org/apache/dubbo/common/utils/DefaultSerializeClassChecker.java#L33 https://dubbo.apache.org/zh-cn/overview/mannual/java-sdk/advanced-features-and-usage/security/class-check/

got it, I will refactor it

2024-05-08 03:35 UTC, AlbumenJ requested changes

2024-05-08 03:35 UTC, AlbumenJ commented on dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/yaml/YamlCodeCTest.java
> + * @author yuluo
Please remove the author tag. THX

2024-06-23 14:42 UTC, yuluo-yx commented on dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/yaml/YamlCodeCTest.java
> + * @author yuluo
got it

2024-06-24 09:58 UTC, AlbumenJ requested changes

2024-06-24 09:58 UTC, AlbumenJ commented on dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/yaml/YamlCodeCTest.java
> +import org.yaml.snakeyaml.error.YAMLException;
I'm curious if adding these test cases would be beneficial for Dubbo?

2024-06-24 09:59 UTC, AlbumenJ commented
For https://github.com/apache/dubbo/issues/13799, we should test it through a complete RPC

2025-06-24 11:04 UTC, closed without merging