fixed pojoutils string class issue
apache/dubbo pull request #14102
Opened 2024-04-19 02:33 UTC by zcbbpo

Hi 
## Environment

- Dubbo version: 3.2.0
- Operating System version: mac os 12.2
- Java version: 21

when i use telnet to invoke , it will throw exception
`dubbo>invoke com.xxx.api.PService.check({"value": 1, "class": "java.lang.Long"}, {"value": 1, "class": "java.lang.Long"}, {"value": "abc", "class": "java.lang.String"}, {"value": "c", "class": "java.lang.String"})`
**Its response:**
![image](https://github.com/apache/dubbo/assets/54526829/0d895cbd-a4d4-4894-b8d1-5cb5cd3107aa)

i have add this code for fixed issue: org.apache.dubbo.common.utils.PojoUtils#realize0
![image](https://github.com/apache/dubbo/assets/54526829/d0565bd0-4e0b-46b3-8f22-86ef0685ac8c)

### this is test case
![image](https://github.com/apache/dubbo/assets/54526829/d1a99b5c-4801-4e3c-ac6e-3e86523a0a6f)

## Brief changelog

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2024-05-08 03:08 UTC, AlbumenJ commented
![image](https://github.com/apache/dubbo/assets/9292748/bacaee06-38bf-43e9-b089-145fcdde5523)
Please fix the code style

2024-05-08 06:12 UTC, AlbumenJ commented
![image](https://github.com/apache/dubbo/assets/9292748/9977547d-418e-4aa6-b36d-83ef9ab81058)

2024-05-08 07:16 UTC, zcbbpo commented
![image](https://github.com/apache/dubbo/assets/54526829/a9f5b468-1b50-4f6d-bfc2-d8a8319438fe)
is use jdk21 to run unit test? 
it's should requred to add jvm args "--add-opens java.base/java.math=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED"? please help to check

2024-05-08 07:24 UTC, AlbumenJ commented
> ![image](https://private-user-images.githubusercontent.com/54526829/328790849-a9f5b468-1b50-4f6d-bfc2-d8a8319438fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTMyOTIsIm5iZiI6MTcxNTE1Mjk5MiwicGF0aCI6Ii81NDUyNjgyOS8zMjg3OTA4NDktYTlmNWI0NjgtMWI1MC00ZjZkLWJmYzItZDhhODMxOTQzOGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA3MjMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOTAzZjE3OWNkMjYwMzJkYTQ3YjdmNzhkY2M5NDBlMTc4NGZmN2YzOTY4M2Y2MjYwZTJjNzk3ZjZlMGEzNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._qjtiS3kH8bxnc9zaZoFOfyMbzq3cX4Lf9KVvU5xBM4) is use jdk21 to run unit test? it's should requred to add jvm args "--add-opens java.base/java.math=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED"? please help to check

As design, Dubbo itself should not require any `--add-opens` configuration

2024-05-08 08:22 UTC, zcbbpo commented
in this method: org.apache.dubbo.common.utils.PojoUtils#getField
![image](https://github.com/apache/dubbo/assets/54526829/3f5f10c1-cf4a-4e36-ab92-e0f88b4e06d9)
when the acls is jdk class , we cannot modify field accessible. could we can add this code to ignore jdk classes?

2024-05-08 08:24 UTC, zcbbpo commented
![image](https://github.com/apache/dubbo/assets/54526829/7971a001-1c61-4eb9-a6b1-5ff382908d93)
add check it's if jdk classes

2024-06-24 10:03 UTC, AlbumenJ requested changes

2024-06-24 10:03 UTC, AlbumenJ commented on dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
> +                if (!Modifier.isPublic(result.getModifiers()) && acls.getClassLoader() != null) {
For JDK internal classes, even if they don't fail here, they will eventually fail.

2025-06-24 10:59 UTC, closed without merging