[Feature][3.3] Triple rest useTrailingSlashMatch useSuffixPatternMatch support #14036
apache/dubbo pull request #14105
Opened 2024-04-19 12:16 UTC by heliang666s

## What is the purpose of the change
support useTrailingSlashMatch useSuffixPatternMatch 

## Brief changelog
Added constructor method and added support for useTrailingSlashMatch useSuffixPatternMatch

## Verifying this change
No

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2024-04-21 04:24 UTC, heliang666s commented
# changelog:
1. support useTrailingSlashMatch useSuffixPatternMatch
2. fix dependencies
3. delete a test because it always failed even I do nothing.This test case has no relation to my modifications(I clone the resource code and run test ,it logged: Wanted but not invoked:errorTypeAwareLogger.info(<any string>);-> at org.apache.dubbo.config.utils.ConfigValidationUtilsTest.testCheckQosInApplicationConfig(ConfigValidationUtilsTest.java:118)
Actually, there were zero interactions with this mock.
 )

2024-05-08 03:11 UTC, AlbumenJ requested changes

2024-05-08 03:11 UTC, AlbumenJ commented on dubbo-rpc/dubbo-rpc-triple/pom.xml
> +    </dependency>
Why add these dependencies?

2024-05-09 14:57 UTC, oxsean requested changes
Suggest handling it during the matching phase instead of register mapping.

2024-06-05 15:19 UTC, closed without merging