feat:Add online and ready functions based on Spring Boot Actuator
apache/dubbo pull request #14399
Opened 2024-07-08 06:35 UTC by JinQian1024

## What is the purpose of the change
It implements the online (to be improved) and ready functions based on Spring Boot Actuator and equivalent to the QoS functions

## Brief changelog

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2024-07-10 07:03 UTC, AlbumenJ requested changes

2024-07-10 07:03 UTC, AlbumenJ commented on dubbo-spring-boot/dubbo-spring-boot-actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/autoconfigure/DubboEndpointAnnotationAutoConfiguration.java
> +        value = "classpath:/META-INF/dubbo-endpoints-default" + ".properties")
Why change this

2024-07-10 07:03 UTC, AlbumenJ commented on dubbo-spring-boot/dubbo-spring-boot-actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/endpoint/DubboOnlineEndpoint.java
> +@Endpoint(id = "dubboonline")
offline is also useful

2024-08-05 15:14 UTC, CrazyHZM requested changes

2024-08-05 15:14 UTC, CrazyHZM commented on dubbo-spring-boot/dubbo-spring-boot-compatible/actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/endpoint/metadata/DubboGetEnabledRouterMetadata.java
> +public class DubboGetEnabledRouterMetadata {
Named for ServiceOfEnabledRouterSnapshot better, here don't have to add metadata suffix.
The same as below.

2024-08-05 15:20 UTC, CrazyHZM requested changes

2024-08-05 15:20 UTC, CrazyHZM commented on dubbo-spring-boot/dubbo-spring-boot-compatible/actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/endpoint/metadata/DubboOfflineMetadata.java
> +    public Map<String, Object> baseOffline(
The operation here should depend on QoS and should not be rewritten.

2024-09-12 02:07 UTC, closed without merging