Support users to customize JsonUtil through JsonUtilCustomizer
apache/dubbo pull request #14508
Opened 2024-08-09 15:40 UTC by oxsean

## What is the purpose of the change
In http scenario, the user wants to customize the JSON conversion.

## Brief changelog

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2024-08-11 01:25 UTC, CrazyHZM requested changes
I can't entirely agree with this `JsonUtilCustomizer.` It increases the complexity of jsonutil and allows users to re-implement jsonutil if they want to customize some parameters

2024-08-11 02:48 UTC, oxsean commented
> I can't entirely agree with this `JsonUtilCustomizer.` It increases the complexity of jsonutil and allows users to re-implement jsonutil if they want to customize some parameters

It's really something we need to consider, This feature is for rest, the complexity is relative, for the end user to use `JsonUtilCustomizer ` will make the customization easier, otherwise, because fastjson all use static parameters, customization is hard.

2024-08-20 09:46 UTC, AlbumenJ requested changes

2024-08-20 09:46 UTC, AlbumenJ commented on dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/HttpJsonUtils.java
> +    private static JsonUtil jsonUtil;
Prevent use static here

2024-09-01 07:20 UTC, CrazyHZM approved these changes

2024-09-01 07:20 UTC, CrazyHZM commented
@oxsean The pr title could be changed.

2024-09-04 11:03 UTC, AlbumenJ commented
@chickenlj PTAL

2024-09-06 09:13 UTC, chickenlj approved these changes
LGTM.

2024-09-06 09:14 UTC, merged