Feature/state router
apache/dubbo pull request #6844
Opened 2020-10-28 11:41 UTC by panxiaojun233

## What is the purpose of the change

XXXXX

## Brief changelog

XXXXX

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2021-04-30 04:54 UTC, AlbumenJ requested changes

2021-04-30 04:54 UTC, AlbumenJ commented on dubbo-cluster/pom.xml
> +            <version>0.9.0</version>
pls move this field to `dubbo-dependencies` module

2021-04-30 04:54 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
> +        // FIXME 看一下高版本的RoaringBitMap，是否有内置函数支持更高效的遍历
pls comment in English

2021-04-30 04:54 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
> +                executorRepository.getPoolRouterExecutor().execute(new Runnable() {
is this executor necessary?

2021-04-30 04:54 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
> +            Thread.currentThread().interrupt();
is this works? Just wrapped with `RPCException` and throw it would be better?

2021-04-30 04:54 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
> +        // 1、多个服务并行执行 buildCache
Please comment in English

2021-04-30 04:54 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
> +                LOOP_THREAD_POOL.submit(new Runnable() {
Try make this Runnable as a static class reference or lambda reference. Reduce inner class creation.

2021-04-30 04:54 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/AddrCache.java
> +package org.apache.dubbo.rpc.cluster.router.state;
Please add Apache License header

2021-04-30 04:54 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/BitList.java
> +package org.apache.dubbo.rpc.cluster.router.state;
Please add Apache License header

2021-04-30 04:54 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/RouterCache.java
> +package org.apache.dubbo.rpc.cluster.router.state;
Please add Apache License header

2021-04-30 04:54 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/StateRouterFactory.java
> +package org.apache.dubbo.rpc.cluster.router.state;
Please add Apache License header

2021-04-30 04:54 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagDynamicStateRouter.java
> +            // 地址为空，则动态路由不生效，直接看静态路由
Please comment in English

2021-04-30 04:54 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagDynamicStateRouter.java
> +        ConcurrentHashMap<String, BitList<Invoker<T>>> addrPool = new ConcurrentHashMap<>();
try specify inital size

2021-05-12 03:22 UTC, guohao requested changes

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
> +        CountDownLatch cdl = new CountDownLatch(stateRouters.size());
unused var

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
> +        final AtomicBoolean poolSuccess = new AtomicBoolean(true);
remove this var

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
> +            RouterCache routerCache;
```suggestion
          
            try{
              for(;;)
              this.cache.set()
              }catch{
              }
```

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
> +        RouterCache routerCache = null;
```suggestion
        RouterCache routerCache ;
```

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
> +        if (cache == null || cache.getCache() == null || cache.getInvokers() == null || cache.getCache().get(routerName)
```suggestion
              return cache == null || cache.getCache() == null || cache.getInvokers() == null || 
                cache.getCache().get(routerName) == null;
```

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/StateRouter.java
> +public interface StateRouter extends Comparable<StateRouter> {
```suggestion
public interface StateRouter<T> extends Comparable<StateRouter<T>>

```

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/StateRouter.java
> +    <T> BitList<Invoker<T>> route(BitList<Invoker<T>> invokers, RouterCache cache, URL url, Invocation invocation)
```suggestion
BitList<Invoker<T>> route(BitList<Invoker<T>> invokers, RouterCache cache, URL url, Invocation invocation)

```

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/StateRouter.java
> +    <T> RouterCache pool(List<Invoker<T>> invokers);
```suggestion
     RouterCache pool(List<Invoker<T>> invokers);

```

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/StateRouterFactory.java
> +    StateRouter getRouter(URL url, RouterChain chain);
```suggestion
       <T> StateRouter<T> getRouter(URL url, RouterChain<T> chain);
```

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/RouterCache.java
> +public class RouterCache {
```suggestion
RouterCache<T> 
```

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/RouterCache.java
> +    public void setAddrPool(
```suggestion
       public void setAddrPool(ConcurrentHashMap<String, BitList<Invoker<T>>> addrPool) {
```

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/RouterCache.java
> +    protected ConcurrentHashMap<String, BitList<Invoker>> addrPool = new ConcurrentHashMap<>();
Use a constant empty map instead of creating a new one

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/RouterCache.java
> +    protected ConcurrentHashMap<String, BitList<Invoker>> addrPool = new ConcurrentHashMap<>();
ConcurrentHashMap -> ConcurrentMap

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagDynamicStateRouter.java
> +        routerCache.setAddrPool((ConcurrentHashMap)addrPool);
```suggestion
        routerCache.setAddrPool(addrPool);
```

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagStaticStateRouter.java
> +    private static final String RULE_SUFFIX = ".tag-router";
unused field

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagStaticStateRouter.java
> +    private static final Logger logger = LoggerFactory.getLogger(TagStaticStateRouter.class);
unused field

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagStaticStateRouter.java
> +        // FIXME
Fix what?

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagStaticStateRouter.java
> +        routerCache.setAddrPool((ConcurrentHashMap)addrPool);
```suggestion
        routerCache.setAddrPool(addrPool);
```

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/AddrCache.java
> +public class AddrCache {
```suggestion
public class AddrCache<T> {

```

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/AddrCache.java
> +    protected List<Invoker> invokers;
```suggestion
       protected List<Invoker<T>> invokers;

```

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/AddrCache.java
> +    protected ConcurrentHashMap<String, RouterCache> cache = new ConcurrentHashMap<>();
Use constant empty map

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/AddrCache.java
> +    public void setCache(
```suggestion
       public void setCache(ConcurrentHashMap<String, RouterCache> cache) {

```

2021-05-12 03:22 UTC, guohao commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/AbstractStateRouter.java
> +        return invokers == null || invokers.size() <= 0;
```suggestion
        return invokers == null || invokers.isEmpty();
```

2021-05-12 03:24 UTC, guohao commented on dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/DefaultExecutorRepository.java
> +import java.util.concurrent.ScheduledThreadPoolExecutor;
unused

2021-05-14 09:11 UTC, guohao approved these changes
LGTM

2021-05-14 16:30 UTC, AlbumenJ approved these changes

2021-05-14 16:30 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagStaticStateRouterFactory.java
> +    public static final String NAME = "tag-dynamic";
the `NAME` should be `tag-static`

2021-05-18 09:13 UTC, merged