fix OOM
apache/dubbo pull request #6848
Opened 2020-10-29 06:04 UTC by luckyyuandm

Change-Id: I4fce78be15179722fea1fa645495783c60b28573
Signed-off-by: yuandm <yuandm@foxmail.com>

## What is the purpose of the change

fix OOM when deserializing data

## Brief changelog

XXXXX

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2020-10-30 16:53 UTC, kimmking approved these changes

2020-10-30 16:53 UTC, kimmking commented on dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectInput.java
> +		// TODO Auto-generated method stub
remove the comment

2020-10-30 16:53 UTC, kimmking commented on dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectInput.java
> +public class Hessian2ObjectInput implements ObjectInput,Cleanable {
keep a blank before Cleanable

2020-10-30 16:56 UTC, kimmking requested changes

2020-10-30 16:56 UTC, kimmking commented on dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectOutput.java
> +		// TODO Auto-generated method stub
remove comment

2020-10-30 16:56 UTC, kimmking commented on dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectOutput.java
> +public class Hessian2ObjectOutput implements ObjectOutput,Cleanable {
keep a blank before Cleanable

2020-11-02 12:32 UTC, luckyyuandm commented on dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectInput.java
> +		// TODO Auto-generated method stub
ok

2020-11-02 12:32 UTC, luckyyuandm commented on dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectOutput.java
> +		// TODO Auto-generated method stub
ok

2020-11-02 12:32 UTC, luckyyuandm commented on dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectOutput.java
> +public class Hessian2ObjectOutput implements ObjectOutput,Cleanable {
ok

2020-11-02 12:33 UTC, luckyyuandm commented on dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectInput.java
> +public class Hessian2ObjectInput implements ObjectInput,Cleanable {
ok

2021-03-14 08:29 UTC, AlbumenJ approved these changes
LGTM.

2021-03-14 08:29 UTC, merged