add ClusterRules LoadbalanceRules to dubbo common #7531
apache/dubbo pull request #7534
Opened 2021-04-12 04:20 UTC by rockit-ba

add ClusterRules 、LoadbalanceRules for cluster and  loadbalance properties。

We can user like 
`@DubboService(loadbalance = LoadbalanceRules.RANDOM,cluster = ClusterRules.FAIL_BACK)`

It was like this before
`@DubboService(loadbalance = "random",cluster = "failback")`

2021-04-12 05:18 UTC, rockit-ba commented
> add ClusterRules 、LoadbalanceRules for cluster and loadbalance properties。
> 
> We can user like
> `@DubboService(loadbalance = LoadbalanceRules.RANDOM,cluster = ClusterRules.FAIL_BACK)`
> 
> It was like this before
> `@DubboService(loadbalance = "random",cluster = "failback")`

2021-04-12 06:08 UTC, AlbumenJ requested changes

2021-04-12 06:08 UTC, AlbumenJ commented on dubbo-common/src/main/java/org/apache/dubbo/common/constants/ClusterRules.java
> +package org.apache.dubbo.common.constants;
pls add asf license header

2021-04-12 06:08 UTC, AlbumenJ commented on dubbo-common/src/main/java/org/apache/dubbo/common/constants/ClusterRules.java
> + * @author lucky-pan
please remove author tag, thx

2021-04-12 06:08 UTC, AlbumenJ commented on dubbo-common/src/main/java/org/apache/dubbo/common/constants/LoadbalanceRules.java
> +package org.apache.dubbo.common.constants;
also for this file

2021-04-12 06:09 UTC, AlbumenJ commented
Please merge the latest master branch into your branch and it can trigger github actions correctly.

2021-04-12 06:59 UTC, rockit-ba commented
> Please merge the latest master branch into your branch and it can trigger github actions correctly.

OK

2021-04-12 17:28 UTC, horizonzy commented on dubbo-common/src/main/java/org/apache/dubbo/config/annotation/Reference.java
> +    String loadbalance() default LoadbalanceRules.RANDOM;
maintain the original logic, use empty str.

2021-04-13 00:39 UTC, rockit-ba commented on dubbo-common/src/main/java/org/apache/dubbo/config/annotation/Reference.java
> +    String loadbalance() default LoadbalanceRules.RANDOM;
OK（前辈睡的有点晚/捂脸）

2021-04-13 06:42 UTC, xiaoheng1 reviewed
Error:  /home/runner/work/dubbo/dubbo/dubbo-common/src/main/java/org/apache/dubbo/config/annotation/Service.java:30:15: Unused import - org.apache.dubbo.common.constants.CommonConstants.DEFAULT_LOADBALANCE. [UnusedImports]
Error:  /home/runner/work/dubbo/dubbo/dubbo-common/src/main/java/org/apache/dubbo/config/annotation/DubboService.java:30:15: Unused import - org.apache.dubbo.common.constants.CommonConstants.DEFAULT_LOADBALANCE. [UnusedImports]

please handle unused imports.

2021-04-13 07:22 UTC, rockit-ba commented
> Error: /home/runner/work/dubbo/dubbo/dubbo-common/src/main/java/org/apache/dubbo/config/annotation/Service.java:30:15: Unused import - org.apache.dubbo.common.constants.CommonConstants.DEFAULT_LOADBALANCE. [UnusedImports]
> Error: /home/runner/work/dubbo/dubbo/dubbo-common/src/main/java/org/apache/dubbo/config/annotation/DubboService.java:30:15: Unused import - org.apache.dubbo.common.constants.CommonConstants.DEFAULT_LOADBALANCE. [UnusedImports]
> 
> please handle unused imports.

OK

2021-04-13 08:45 UTC, xiaoheng1 approved these changes
LGTM

2021-04-13 09:32 UTC, horizonzy approved these changes
LGTM.

2021-04-16 03:40 UTC, merged