[3.0]Cleanup EventDispatcher mechanism
apache/dubbo pull request #7677
Opened 2021-05-06 02:47 UTC by kevinw66

## What is the purpose of the change

Cleanup EventDispatcher mechanism

2021-06-04 03:07 UTC, chickenlj requested changes

2021-06-04 03:07 UTC, chickenlj commented on dubbo-registry/dubbo-registry-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/KubernetesServiceDiscovery.java
> +            watchEndpoints(serviceName);
Does this change still match the original meaning?

The original impl only notify one listener while the new one notifies all listeners.

2021-06-04 03:07 UTC, chickenlj commented on dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscoveryChangeWatcher.java
> +                zookeeperServiceDiscovery.dispatchServiceInstancesChangedEvent((ServiceInstancesChangedEvent)rawAddresses);
Can listeners in Watcher being replaced with listeners in ServiceDiscovery?

Watcher is bound to one single service while ServiceDiscovery is shared among services.

2021-06-04 09:51 UTC, kevinw66 commented on dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/AbortPolicyWithReport.java
> -        dispatchThreadPoolExhaustedEvent(msg);
done

2021-06-08 09:45 UTC, chickenlj submitted a review, later dismissed
LGTM.

2021-06-08 16:23 UTC, chickenlj approved these changes
LGTM.

2021-06-08 16:23 UTC, merged