add a unit test for AvailableClusterInvoker
apache/dubbo pull request #7883
Opened 2021-05-27 03:52 UTC by hadley0828

## What is the purpose of the change
issue #7882

## Brief changelog
add AvailableClusterInvokerTest.java

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [x] GitHub Actions works fine on your own branch.
- [x] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2021-05-27 04:31 UTC, icankeep reviewed
it would be better to add a case that invoker1 is unavailable

2021-05-27 04:31 UTC, icankeep commented on dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AvailableClusterInvokerTest.java
> +    private void resetInvokerToException() {
unused method should remove

2021-06-03 08:58 UTC, chickenlj requested changes

2021-06-03 08:58 UTC, chickenlj commented on dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AvailableClusterInvokerTest.java
> +import org.apache.dubbo.rpc.*;
avoid using import *

2021-06-08 09:58 UTC, chickenlj commented
Closed no feedbacks for days.

2021-06-08 09:58 UTC, closed without merging