Replace list with set in ExtensionLoader
apache/dubbo pull request #7926
Opened 2021-05-30 12:31 UTC by icankeep

## What is the purpose of the change

issue: #7925 
Replace list with set in ExtensionLoader

## Brief changelog

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2021-05-31 02:34 UTC, AlbumenJ requested changes

2021-05-31 02:34 UTC, AlbumenJ commented on dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
> +        for (String name : names) {
Iterator with set is lack of performance. Sometimes it will create a lot of iterator objects.

2021-05-31 12:38 UTC, icankeep commented on dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
> +        for (String name : names) {
但是Set好像只能用iterator遍历了，这里的改动主要是觉得多次执行了这个`names.contains(name)`
List改为Set可能会好些

2021-06-01 14:59 UTC, AlbumenJ commented on dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
> +        for (String name : names) {
`CollectionUtils.ofSet` is based on `LinkedHashSet`. So, it doesn't have this problem

2021-06-01 15:00 UTC, merged