Update NacosServiceDiscovery.java Remove useless code
apache/dubbo pull request #8077
Opened 2021-06-16 12:13 UTC by Colin678

Remove useless code

## What is the purpose of the change

## Brief changelog

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2021-06-21 02:20 UTC, AlbumenJ commented
please resolve confilcts

2021-06-21 12:27 UTC, Colin678 commented
resolve confilcts @AlbumenJ

2021-08-16 12:13 UTC, BurningCN commented
pls remove unused import 
![image](https://user-images.githubusercontent.com/43363120/129561980-dc1c0268-3071-4310-8db4-772db5c6a7e7.png)

2021-08-19 10:54 UTC, 24kpure commented
Why not merge 5 commit into one？

2021-08-19 10:59 UTC, Colin678 commented
The interval is too long，is not a pr？ QwQ@24kpure

2021-08-20 06:02 UTC, 24kpure commented
> The interval is too long，is not a pr？ QwQ@24kpure

You'd better  have a look at checklist.
`Each commit in the pull request should have a meaningful subject line and body`

2021-08-20 06:10 UTC, Colin678 commented
I give up ，I will find a more meaningful submission@24kpure

2021-08-23 05:46 UTC, AlbumenJ requested changes

2021-08-23 05:46 UTC, AlbumenJ commented on dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceDiscovery.java
> +import static org.apache.dubbo.registry.nacos.util.NacosNamingServiceUtils.*;
Please do not use comma inport in Dubbo project

2022-03-16 01:38 UTC, closed without merging