Add instance url scopeModel
apache/dubbo pull request #9290
Opened 2021-11-17 14:18 UTC by CrazyHZM

## What is the purpose of the change

## Brief changelog

## Verifying this change

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2021-12-02 11:13 UTC, AlbumenJ approved these changes

2021-12-06 05:22 UTC, AlbumenJ requested changes

2021-12-06 05:22 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/DefaultFilterChainBuilder.java
> +        if (moduleModels != null && moduleModels.size() != 0) {
If moduleModels' size is 1, directly use result to reduce memory allocation.

2021-12-06 05:22 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/DefaultFilterChainBuilder.java
> +                filters.addAll(tempFilters);
Filters need to be sorted and de-duplicated.

2021-12-06 05:22 UTC, AlbumenJ commented on dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/DefaultFilterChainBuilder.java
> +            moduleModels = ((ApplicationModel) scopeModel).getModuleModels();
Use `getPubModuleModels()` instead.

2021-12-14 06:53 UTC, chickenlj commented
https://github.com/apache/dubbo/issues/9403

2021-12-15 06:50 UTC, chickenlj commented
I think `getModuleModelsFromUrl` is a little bit weird. It can be better if the module model can be passed through the API method.

2021-12-15 06:53 UTC, merged